import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { a: 3, b: 2, s: 1 },
      { a: 1, b: 2, s: -1 },
      { a: 5, b: 5, s: -1 },
    ],
    2: [
      { a: 9, b: 2, s: 1 },
      { a: 12, b: 9, s: -1 },
      { a: 15, b: 3, s: 1 },
    ],
    3: [
      { ta: 3, oa: 2, tb: 5, ob: 8 },
      { ta: 8, oa: 6, tb: 5, ob: 5 },
      { ta: 5, oa: 6, tb: 9, ob: 4 },
    ],
    4: [
      { ta: 5, oa: 0, ob: 9, tb: 1, s: -1 },
      { ta: 4, oa: 1, ob: 6, tb: 1, s: -1 },
      { ta: 6, oa: 5, ob: 6, tb: 4, s: -1 },
    ],
    5: [
      { F: 1, a: 82, x: 11, s: 1 },
      { F: 2, a: 39, x: 22, s: -1 },
      { F: 3, b: 42, c: 57, s: 1 },
    ],
    6: [
      { O: "left", L: 56, a: 14, delta: 5, d: 17 },
      { O: "right", L: 80, a: 19, delta: 7, d: 10 },
      { O: "equal", L: 36, a: 21, d: 11 },
    ],
    7: [
      { op: "+", p: 100, s: 1, ha: 5, hb: 1, ta: 4, tb: 5, oa: 8, ob: 9 },
      {
        op: "−",
        p: 10,
        s: 1,
        ha: 7,
        hb: 3,
        zflag: 2,
        ta: 2,
        tb: 2,
        oa: 5,
        ob: 9,
      },
      { op: "−", p: 10, s: -1, ha: 7, hb: 6, zflag: 1, tb: 7, oa: 3, ob: 9 },
    ],
    8: [
      {
        n: 221,
        a: 161,
        b: 149,
        order: "gain-first",
        P: "Mia",
        item: "stamps",
        gain: "collects",
        lose: "gives away",
      },
      {
        n: 168,
        a: 155,
        b: 26,
        order: "lose-first",
        P: "Dev",
        item: "beads",
        gain: "collects",
        lose: "sells",
      },
      {
        n: 495,
        a: 34,
        b: 17,
        order: "lose-first",
        P: "Ava",
        item: "stamps",
        gain: "buys",
        lose: "loses",
      },
    ],
    9: [
      { F: 1, a: 86, b: 80, d: 44, s: 1 },
      { F: 1, a: 83, b: 19, d: 43, s: -1 },
      { F: 2, b: 56, c: 99, a: 18, s: 1 },
    ],
    10: [
      {
        rel1: "more",
        rel2: "fewer",
        x: 163,
        y: 19,
        z: 10,
        A: "Eli",
        B: "Uma",
        C: "Raj",
        item: "shells",
      },
      {
        rel1: "fewer",
        rel2: "more",
        x: 232,
        y: 22,
        z: 28,
        A: "Tia",
        B: "Dev",
        C: "Mia",
        item: "stamps",
      },
      {
        rel1: "fewer",
        rel2: "fewer",
        x: 297,
        y: 126,
        z: 63,
        A: "Kai",
        B: "Cleo",
        C: "Gus",
        item: "marbles",
      },
    ],
  },
  extra: [
    {
      level: 8,
      vars: {
        n: 200,
        a: 30,
        b: 60,
        order: "gain-first",
        P: "Ben",
        item: "cards",
        gain: "finds",
        lose: "uses",
      },
      prompt:
        "Ben has 200 cards. Ben finds 30 more, then uses 60. How many cards does Ben have now?",
      choices: ["170", "230", "290"],
      correct: "170",
    },
    {
      level: 10,
      vars: {
        rel1: "more",
        rel2: "more",
        x: 100,
        y: 20,
        z: 30,
        A: "Ava",
        B: "Ben",
        C: "Cleo",
        item: "cards",
      },
      prompt:
        "Ava has 100 cards. Ben has 20 more than Ava. Cleo has 30 more than Ben. How many cards does Cleo have?",
      choices: ["150", "90", "130"],
      correct: "150",
    },
    {
      level: 10,
      vars: {
        rel1: "more",
        rel2: "more",
        x: 50,
        y: 30,
        z: 15,
        A: "Ava",
        B: "Ben",
        C: "Cleo",
        item: "cards",
      },
      prompt:
        "Ava has 50 cards. Ben has 30 more than Ava. Cleo has 15 more than Ben. How many cards does Cleo have?",
      choices: ["95", "65", "80"],
      correct: "95",
    },
  ],
} satisfies Examples;
