import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { a: 6, b: 9, s: -1 },
      { a: 8, b: 4, s: 1 },
      { a: 9, b: 8, s: -1 },
    ],
    2: [
      { a: 6, b: 9, s: -1 },
      { a: 8, b: 6, s: 1 },
      { a: 8, b: 5, s: 1 },
    ],
    3: [
      { F: 1, a: 6, b: 3, s: -1 },
      { F: 1, a: 5, b: 6, s: 1 },
      { F: 2, a: 6, b: 2, s: 1 },
    ],
    4: [
      { F: 1, a: 6, s: -1 },
      { F: 2, a: 9, s: -1 },
      { F: 3, a: 3, b: 7, s: -1 },
    ],
    5: [
      { tm: 5, om: 2, c: 6, s: 1 },
      { tm: 3, om: 3, c: 8, s: 1 },
      { tm: 9, om: 3, c: 9, s: 1 },
    ],
    6: [
      { form: "A", P: "Zoe", s: -1, r: 9, m: 6, item: "stickers" },
      { form: "A", P: "Jo", s: -1, r: 7, m: 6, item: "tiles" },
      {
        form: "B",
        P: "Omar",
        s: 1,
        g: 3,
        q: 11,
        item: "cookies",
        holder: "trays",
      },
    ],
    7: [
      { a: 86, b: 9 },
      { a: 39, b: 4 },
      { a: 66, b: 4 },
    ],
    8: [
      { u: 18, v: 29, s: 1 },
      { u: 16, v: 18, s: -1 },
      { u: 28, v: 14, s: 1 },
    ],
    9: [
      { d: 4, zflag: 2, q: 228, s: 1, s2: 1 },
      { d: 9, zflag: 3, q: 82, s: -1, s2: -1 },
      { d: 6, zflag: 1, h: 1, o: 1, s: -1 },
    ],
    10: [
      { b: 4, n: 79, ask: "needed", scene: ["marbles", "jar"] },
      { b: 9, n: 68, ask: "full", scene: ["children", "bus"] },
      { b: 6, n: 155, ask: "left", scene: ["books", "box"] },
    ],
  },
  extra: [
    {
      level: 1,
      vars: { a: 2, b: 4, s: -1 },
      prompt: "2 × 4 = ?",
      choices: ["8", "10", "6"],
      correct: "8",
    },
    {
      level: 1,
      vars: { a: 3, b: 3, s: -1 },
      prompt: "3 × 3 = ?",
      choices: ["9", "12", "6"],
      correct: "9",
    },
    {
      level: 2,
      vars: { a: 2, b: 3, s: 1 },
      prompt: "6 ÷ 3 = ?",
      choices: ["2", "1", "3"],
      correct: "2",
    },
    {
      level: 2,
      vars: { a: 3, b: 2, s: 1 },
      prompt: "6 ÷ 2 = ?",
      choices: ["3", "2", "4"],
      correct: "3",
    },
    {
      level: 3,
      vars: { F: 1, a: 3, b: 2, s: 1 },
      prompt: "3 × ? = 6",
      choices: ["2", "3", "1"],
      correct: "2",
    },
    {
      level: 3,
      vars: { F: 1, a: 2, b: 3, s: 1 },
      prompt: "2 × ? = 6",
      choices: ["3", "4", "2"],
      correct: "3",
    },
    {
      level: 3,
      vars: { F: 2, a: 3, b: 3, s: -1 },
      prompt: "? ÷ 3 = 3",
      choices: ["9", "6", "12"],
      correct: "9",
    },
    {
      level: 3,
      vars: { F: 2, a: 4, b: 2, s: -1 },
      prompt: "? ÷ 2 = 4",
      choices: ["8", "6", "10"],
      correct: "8",
    },
    {
      level: 4,
      vars: { F: 1, a: 7, s: 1 },
      prompt: "7 × 10 = ?",
      choices: ["70", "700", "17"],
      correct: "70",
    },
    {
      level: 4,
      vars: { F: 2, a: 9, s: 1 },
      prompt: "9 × 100 = ?",
      choices: ["900", "9,000", "109"],
      correct: "900",
    },
    {
      level: 4,
      vars: { F: 3, a: 4, b: 6, s: 1 },
      prompt: "40 × 6 = ?",
      choices: ["240", "2,400", "46"],
      correct: "240",
    },
    {
      level: 5,
      vars: { tm: 1, om: 2, c: 5, s: -1 },
      prompt: "12 × 5 = ?",
      choices: ["60", "50", "10"],
      correct: "60",
    },
    {
      level: 6,
      vars: { form: "A", P: "Ben", s: -1, r: 3, m: 3, item: "chairs" },
      prompt: "Ben sets out 3 rows of 3 chairs. How many chairs in total?",
      choices: ["9", "6", "12"],
      correct: "9",
    },
    {
      level: 6,
      vars: { form: "A", P: "Mia", s: 1, r: 4, m: 8, item: "plants" },
      prompt: "Mia sets out 4 rows of 8 plants. How many plants in total?",
      choices: ["32", "12", "40"],
      correct: "32",
    },
    {
      level: 6,
      vars: {
        form: "B",
        P: "Ava",
        s: 1,
        g: 3,
        q: 2,
        item: "beads",
        holder: "bags",
      },
      prompt:
        "Ava shares 6 beads equally among 3 bags. How many beads in each bag?",
      choices: ["2", "3", "1"],
      correct: "2",
    },
    {
      level: 6,
      vars: {
        form: "B",
        P: "Raj",
        s: -1,
        g: 9,
        q: 12,
        item: "stickers",
        holder: "boxes",
      },
      prompt:
        "Raj shares 108 stickers equally among 9 boxes. How many stickers in each box?",
      choices: ["12", "99", "11"],
      correct: "12",
    },
    {
      level: 6,
      vars: {
        form: "B",
        P: "Noor",
        s: 1,
        g: 5,
        q: 7,
        item: "shells",
        holder: "baskets",
      },
      prompt:
        "Noor shares 35 shells equally among 5 baskets. How many shells in each basket?",
      choices: ["7", "30", "8"],
      correct: "7",
    },
    {
      level: 6,
      vars: {
        form: "B",
        P: "Kai",
        s: -1,
        g: 4,
        q: 6,
        item: "marbles",
        holder: "jars",
      },
      prompt:
        "Kai shares 24 marbles equally among 4 jars. How many marbles in each jar?",
      choices: ["6", "20", "5"],
      correct: "6",
    },
    {
      level: 7,
      vars: { a: 50, b: 9 },
      prompt: "50 ÷ 9 = ?",
      choices: ["5 R 5", "5 R 4", "6 R 5"],
      correct: "5 R 5",
    },
    {
      level: 7,
      vars: { a: 21, b: 6 },
      prompt: "21 ÷ 6 = ?",
      choices: ["3 R 3", "4 R 3", "2 R 3"],
      correct: "3 R 3",
    },
    {
      level: 8,
      vars: { u: 20, v: 11, s: -1 },
      prompt: "20 × 11 = ?",
      choices: ["220", "200", "240"],
      correct: "220",
    },
    {
      level: 10,
      vars: { b: 12, n: 101, ask: "needed", scene: ["cupcakes", "tray"] },
      prompt:
        "There are 101 cupcakes. Each tray holds 12 cupcakes. How many trays are needed?",
      choices: ["9", "8", "5"],
      correct: "9",
    },
    {
      level: 10,
      vars: { b: 7, n: 45, ask: "full", scene: ["apples", "basket"] },
      prompt:
        "There are 45 apples. Each basket holds 7 apples. How many baskets are completely full?",
      choices: ["6", "7", "3"],
      correct: "6",
    },
    {
      level: 10,
      vars: { b: 8, n: 30, ask: "left", scene: ["photos", "page"] },
      prompt:
        "There are 30 photos. Each page holds 8 photos. When as many pages as possible are filled, how many photos are left over?",
      choices: ["6", "3", "2"],
      correct: "6",
    },
  ],
} satisfies Examples;
