import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { form: "C", kinds: "QDP", q: 3, d: 2, p: 4 },
      { form: "B", b: 2, kinds: "QN", q: 3, n: 1 },
      { form: "C", kinds: "DNP", d: 4, n: 2, p: 3 },
    ],
    2: [
      { mer: "PM", h: 2, sm: 30, H: 2, M: 30, s: -1, event: "match" },
      { mer: "AM", h: 6, sm: 30, H: 4, M: 0, s: 1, event: "class" },
      { mer: "PM", h: 1, sm: 0, H: 2, M: 30, s: 1, event: "rehearsal" },
    ],
    3: [
      { dir: "SB", pair: "cm/m", s: 1, x: 350, v: "W" },
      { dir: "BS", pair: "g/kg", s: -1, x100: 240 },
      { dir: "BS", pair: "mL/L", s: 1, x100: 150 },
    ],
    4: [
      { B: 10, P: 635, v: "B", item: "book" },
      { B: 20, P: 1240, v: "D", item: "mug" },
      { B: 10, P: 385, v: "D", s: -1, item: "kite" },
    ],
    5: [
      { h1: 10, m1: 45, H: 2, M: 35, v: "W", s: -1, event: "hike" },
      { h1: 9, m1: 50, H: 2, M: 45, v: "L", s: 1, event: "film" },
      { h1: 14, m1: 25, H: 4, M: 40, v: "W", s: 1, event: "film" },
    ],
    6: [
      { form: "M", pair: "ft/in", a: 2, b: 7, v: "L" },
      { form: "M", pair: "h/min", a: 3, b: 20, v: "L" },
      { form: "S", pair: "lb/oz", a: 2, b: 8 },
    ],
    7: [
      { mode: "A", pair: "g/kg", X100: 139 },
      { mode: "B", pair: "min/h", X100: 250 },
      { mode: "E", pair: "mm/cm", X100: 850 },
    ],
    8: [
      { k: 3, p: 245, B: 10, s: -1, name: "Fay", items: "candles" },
      { k: 5, p: 145, B: 20, s: 1, name: "Kai", items: "markers" },
      { k: 4, p: 290, B: 50, s: 1, name: "Leo", items: "candles" },
    ],
    9: [
      { h: 23, m: 15, H: 2, M: 30, s: 1 },
      { h: 9, m: 20, H: 3, M: 55, s: -1 },
      { h: 10, m: 30, H: 2, M: 0, s: 1 },
    ],
    10: [
      {
        mode: "A",
        n1: 4,
        n2: 8,
        t: 190,
        u1: 185,
        u2: 192,
        item: "batteries",
      },
      { mode: "S", n1: 5, n2: 6, u: 170, item: "apples" },
      { mode: "B", n1: 4, n2: 7, t: 180, u1: 182, u2: 177, item: "bagels" },
    ],
  },
  extra: [
    {
      level: 1,
      vars: { form: "B", b: 1, kinds: "QD", q: 1, d: 3 },
      prompt: "How much money is 1 $1 bill, 1 quarter and 3 dimes?",
      choices: ["$1.55", "$1.40", "$2.00"],
      correct: "$1.55",
    },
    {
      level: 1,
      vars: { form: "C", kinds: "QDN", q: 1, d: 2, n: 3 },
      prompt: "How much money is 1 quarter, 2 dimes and 3 nickels?",
      choices: ["$0.60", "$0.65", "$1.50"],
      correct: "$0.60",
    },
    {
      level: 1,
      vars: { form: "C", kinds: "QNP", q: 2, n: 1, p: 1 },
      prompt: "How much money is 2 quarters, 1 nickel and 1 penny?",
      choices: ["$0.56", "$0.61", "$0.40"],
      correct: "$0.56",
    },
    {
      level: 1,
      vars: { form: "B", b: 3, kinds: "DP", d: 1, p: 4 },
      prompt: "How much money is 3 $1 bills, 1 dime and 4 pennies?",
      choices: ["$3.14", "$3.09", "$3.50"],
      correct: "$3.14",
    },
    {
      level: 2,
      vars: { mer: "AM", h: 8, sm: 30, H: 2, M: 30, event: "film" },
      prompt:
        "A film starts at 8:30 AM and lasts 2 h 30 min. What time does it end?",
      choices: ["11:00 AM", "10:00 AM", "11:20 AM"],
      correct: "11:00 AM",
    },
    {
      level: 2,
      vars: { mer: "PM", h: 8, sm: 30, H: 3, M: 0, event: "hike" },
      prompt: "A hike starts at 8:30 PM and lasts 3 h. What time does it end?",
      choices: ["11:30 PM", "10:30 PM", "11:00 PM"],
      correct: "11:30 PM",
    },
    {
      level: 2,
      vars: { mer: "PM", h: 12, sm: 0, H: 1, M: 30, s: 1, event: "class" },
      prompt:
        "A class starts at 12:00 PM and lasts 1 h 30 min. What time does it end?",
      choices: ["1:30 PM", "2:30 PM", "1:50 PM"],
      correct: "1:30 PM",
    },
    {
      level: 3,
      vars: { dir: "SB", pair: "mm/cm", x: 7 },
      prompt: "7 mm = ? cm",
      choices: ["0.7 cm", "0.07 cm", "7 cm"],
      correct: "0.7 cm",
    },
    {
      level: 3,
      vars: { dir: "SB", pair: "g/kg", s: -1, x: 2450, v: "N" },
      prompt: "2,450 g = ? kg",
      choices: ["2.45 kg", "24.5 kg", "2,450 kg"],
      correct: "2.45 kg",
    },
    {
      level: 3,
      vars: { dir: "BS", pair: "cm/m", s: 1, x100: 370 },
      prompt: "3.7 m = ? cm",
      choices: ["370 cm", "3,700 cm", "307 cm"],
      correct: "370 cm",
    },
    {
      level: 3,
      vars: { dir: "BS", pair: "m/km", s: -1, x100: 645 },
      prompt: "6.45 km = ? m",
      choices: ["6,450 m", "645 m", "6,045 m"],
      correct: "6,450 m",
    },
    {
      level: 4,
      vars: { B: 5, P: 219, v: "B", item: "puzzle" },
      prompt: "A puzzle costs $2.19. You pay with a $5 bill. How much change?",
      choices: ["$2.81", "$3.81", "$7.81"],
      correct: "$2.81",
    },
    {
      level: 4,
      vars: { B: 20, P: 405, v: "B", s: 1, item: "shirt" },
      prompt: "A shirt costs $4.05. You pay with a $20 bill. How much change?",
      choices: ["$15.95", "$16.95", "$45.95"],
      correct: "$15.95",
    },
    {
      level: 4,
      vars: { B: 10, P: 399, v: "B", s: -1, item: "mug" },
      prompt: "A mug costs $3.99. You pay with a $10 bill. How much change?",
      choices: ["$6.01", "$7.01", "$1.01"],
      correct: "$6.01",
    },
    {
      level: 5,
      vars: { h1: 6, m1: 55, H: 2, M: 10, v: "L", s: -1, event: "class" },
      prompt: "A class starts at 6:55 AM and ends at 9:05 AM. How long is it?",
      choices: ["2 h 10 min", "2 h 5 min", "1 h 10 min"],
      correct: "2 h 10 min",
    },
    {
      level: 5,
      vars: { h1: 19, m1: 55, H: 3, M: 55, v: "W", s: -1, event: "rehearsal" },
      prompt:
        "A rehearsal starts at 7:55 PM and ends at 11:50 PM. How long is it?",
      choices: ["3 h 55 min", "4 h 5 min", "2 h 55 min"],
      correct: "3 h 55 min",
    },
    {
      level: 6,
      vars: { form: "M", pair: "min/s", a: 4, b: 15, v: "B" },
      prompt: "4 min 15 s = ? s",
      choices: ["255 s", "415 s", "1,140 s"],
      correct: "255 s",
    },
    {
      level: 6,
      vars: { form: "M", pair: "ft/in", a: 2, b: 4, v: "L" },
      prompt: "2 ft 4 in = ? in",
      choices: ["28 in", "24 in", "6 in"],
      correct: "28 in",
    },
    {
      level: 6,
      vars: { form: "M", pair: "lb/oz", a: 1, b: 6, v: "L" },
      prompt: "1 lb 6 oz = ? oz",
      choices: ["22 oz", "16 oz", "7 oz"],
      correct: "22 oz",
    },
    {
      level: 6,
      vars: { form: "S", pair: "ft/in", a: 9, b: 11 },
      prompt: "119 in = ? ft ? in",
      choices: ["9 ft 11 in", "11 ft 9 in", "9 ft 1 in"],
      correct: "9 ft 11 in",
    },
    {
      level: 6,
      vars: { form: "S", pair: "h/min", a: 2, b: 30 },
      prompt: "150 min = ? h ? min",
      choices: ["2 h 30 min", "1 h 50 min", "30 h 2 min"],
      correct: "2 h 30 min",
    },
    {
      level: 7,
      vars: { mode: "A", pair: "in/ft", X100: 350 },
      prompt: "Which is longer: 3.5 ft or 35 in?",
      choices: ["3.5 ft", "35 in", "They are equal."],
      correct: "3.5 ft",
    },
    {
      level: 7,
      vars: { mode: "A", pair: "mL/L", X100: 225 },
      prompt: "Which is more: 2.25 L or 225 mL?",
      choices: ["2.25 L", "225 mL", "They are equal."],
      correct: "2.25 L",
    },
    {
      level: 7,
      vars: { mode: "A", pair: "oz/lb", X100: 120 },
      prompt: "Which is heavier: 1.2 lb or 12 oz?",
      choices: ["1.2 lb", "12 oz", "They are equal."],
      correct: "1.2 lb",
    },
    {
      level: 7,
      vars: { mode: "B", pair: "cm/m", X100: 450 },
      prompt: "Which is longer: 4.5 m or 4,500 cm?",
      choices: ["4.5 m", "4,500 cm", "They are equal."],
      correct: "4,500 cm",
    },
    {
      level: 7,
      vars: { mode: "E", pair: "s/min", X100: 150 },
      prompt: "Which is longer: 1.5 min or 90 s?",
      choices: ["1.5 min", "90 s", "They are equal."],
      correct: "They are equal.",
    },
    {
      level: 8,
      vars: { k: 2, p: 995, B: 50, s: -1, name: "Zoe", items: "notebooks" },
      prompt:
        "Zoe buys 2 notebooks at $9.95 each and pays with a $50 bill. How much change?",
      choices: ["$30.10", "$19.90", "$40.05"],
      correct: "$30.10",
    },
    {
      level: 8,
      vars: { k: 5, p: 105, B: 10, s: 1, name: "Noor", items: "socks" },
      prompt:
        "Noor buys 5 socks at $1.05 each and pays with a $10 bill. How much change?",
      choices: ["$4.75", "$5.25", "$3.70"],
      correct: "$4.75",
    },
    {
      level: 9,
      vars: { h: 21, m: 40, H: 3, M: 20, s: -1 },
      prompt: "It is 9:40 PM. What time will it be 3 h 20 min later?",
      choices: ["1:00 AM", "1:00 PM", "12:00 AM"],
      correct: "1:00 AM",
    },
    {
      level: 9,
      vars: { h: 10, m: 0, H: 2, M: 0, s: 1 },
      prompt: "It is 10:00 AM. What time will it be 2 h later?",
      choices: ["12:00 PM", "12:00 AM", "1:00 PM"],
      correct: "12:00 PM",
    },
    {
      level: 9,
      vars: { h: 20, m: 0, H: 6, M: 0, s: 1 },
      prompt: "It is 8:00 PM. What time will it be 6 h later?",
      choices: ["2:00 AM", "2:00 PM", "3:00 AM"],
      correct: "2:00 AM",
    },
    {
      level: 10,
      vars: { mode: "B", n1: 2, n2: 3, t: 60, u1: 64, u2: 57, item: "pens" },
      prompt: "Which is the better buy: 2 pens for $1.28 or 3 pens for $1.71?",
      choices: [
        "2 pens for $1.28",
        "3 pens for $1.71",
        "They are the same value.",
      ],
      correct: "3 pens for $1.71",
    },
    {
      level: 10,
      vars: {
        mode: "A",
        n1: 7,
        n2: 8,
        t: 200,
        u1: 195,
        u2: 204,
        item: "cookies",
      },
      prompt:
        "Which is the better buy: 7 cookies for $13.65 or 8 cookies for $16.32?",
      choices: [
        "7 cookies for $13.65",
        "8 cookies for $16.32",
        "They are the same value.",
      ],
      correct: "7 cookies for $13.65",
    },
  ],
} satisfies Examples;
