import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      {
        form: "T",
        dir: "low",
        p: 9,
        q: 4,
        r: 2,
        days: ["Monday", "Tuesday", "Wednesday"],
        deal: [-9, -4, 2],
      },
      {
        form: "T",
        dir: "high",
        p: 18,
        q: 3,
        r: 7,
        days: ["Monday", "Tuesday", "Wednesday"],
        deal: [-18, -3, 7],
      },
      {
        form: "B",
        dir: "low",
        p: 12,
        q: 5,
        r: 3,
        N1: "Ava",
        N2: "Ben",
        N3: "Cleo",
        deal: [-12, -5, 3],
      },
    ],
    2: [
      { sp: "np", A: 13, B: 5 },
      { sp: "pn", A: 6, B: 14 },
      { sp: "nn", A: 7, B: 5 },
    ],
    3: [
      { sp: "pn", A: 9, B: 4 },
      { sp: "np", A: 15, B: 6 },
      { sp: "nn", A: 4, B: 11 },
    ],
    4: [
      { op: "×", sp: "np", s: 1, m: 7, n: 4 },
      { op: "÷", sp: "nn", s: -1, m: 9, n: 4 },
      { op: "×", sp: "pn", s: -1, m: 6, n: 9 },
    ],
    5: [
      { form: "F1", a: 4, b: 6, c: 3 },
      { form: "F2", c: 3, a: 9, k: 12 },
      { form: "F3", a: 7, b: 5, c: 3, d: 4 },
    ],
    6: [
      { v: "A", a: 5, b: 3, c: 4, d: 6 },
      { v: "B", a: 7, b: 2, c: 5, d: 4 },
      { v: "C", a: 9, b: 4, c: 3, d: 5 },
    ],
    7: [
      { form: "D", a: -13, b: -5 },
      { form: "D", a: -6, b: 9, w: 1 },
      { form: "S", a: -14, b: 6 },
    ],
    8: [
      { ctx: "temp", k: 2, v: "A", s: -8, m1: 5, m2: -9 },
      { ctx: "sub", k: 3, v: "B", s: -21, m1: 10, m2: 2, m3: -7 },
      {
        ctx: "bank",
        k: 3,
        v: "A",
        s: -23,
        m1: -27,
        m2: 25,
        m3: 9,
        N: "Eli",
      },
    ],
    9: [
      { star: "L", o1: "+", o3: "−", a: 2, b: 3, c: 4, d: 5 },
      { star: "M", o1: "−", o3: "+", a: 20, b: 3, c: 4, d: 6 },
      { star: "R", o1: "+", o3: "−", a: 7, b: 4, c: 9, d: 6 },
    ],
    10: [
      { form: "E", shape: "E1", a: 4, b: 7 },
      { form: "E", shape: "E2", a: 3, b: 8 },
      { form: "N", a: 5, b: 3, c: 7, d: 2, e: 4 },
    ],
  },
  extra: [
    {
      level: 1,
      vars: {
        form: "B",
        dir: "high",
        p: 15,
        q: 6,
        r: 9,
        N1: "Omar",
        N2: "Zoe",
        N3: "Kai",
        deal: [9, -15, -6],
      },
      prompt:
        "Omar's balance is $9, Zoe's is −$15, Kai's is −$6. Whose balance is highest?",
      choices: ["Omar", "Zoe", "Kai"],
      correct: "Omar",
    },
    {
      level: 1,
      vars: {
        form: "T",
        dir: "low",
        p: 20,
        q: 11,
        r: 4,
        days: ["Tuesday", "Friday", "Sunday"],
        deal: [4, -11, -20],
      },
      prompt:
        "On Tuesday it was 4 °C, on Friday it was −11 °C, on Sunday it was −20 °C. Which day was coldest?",
      choices: ["Tuesday", "Friday", "Sunday"],
      correct: "Sunday",
    },
    {
      level: 2,
      vars: { sp: "np", A: 3, B: 11 },
      prompt: "What is −3 + 11?",
      choices: ["8", "−8", "14"],
      correct: "8",
    },
    {
      level: 3,
      vars: { sp: "nn", A: 11, B: 4 },
      prompt: "What is −11 − (−4)?",
      choices: ["−7", "−15", "7"],
      correct: "−7",
    },
    {
      level: 4,
      vars: { op: "÷", sp: "pn", s: 1, m: 8, n: 6 },
      prompt: "What is 48 ÷ (−6)?",
      choices: ["−8", "8", "−9"],
      correct: "−8",
    },
    {
      level: 4,
      vars: { op: "×", sp: "nn", s: -1, m: 3, n: 12 },
      prompt: "What is −3 × (−12)?",
      choices: ["36", "−36", "24"],
      correct: "36",
    },
    {
      level: 4,
      vars: { op: "÷", sp: "np", s: -1, m: 2, n: 7 },
      prompt: "What is −14 ÷ 7?",
      choices: ["−2", "2", "−1"],
      correct: "−2",
    },
    {
      level: 5,
      vars: { form: "F4", c: 6, a: 12, k: 3 },
      prompt: "What is 12 + 18 ÷ 6?",
      choices: ["15", "5", "20"],
      correct: "15",
    },
    {
      level: 5,
      vars: { form: "F2", c: 4, a: 24, k: 3 },
      prompt: "What is 24 − 12 ÷ 4?",
      choices: ["21", "3", "−21"],
      correct: "21",
    },
    {
      level: 7,
      vars: { form: "D", a: -4, b: 7, w: 2 },
      prompt: "How far apart are −4 and 7 on the number line?",
      choices: ["11", "−11", "12"],
      correct: "11",
    },
    {
      level: 7,
      vars: { form: "S", a: -3, b: 10 },
      prompt: "What is |−3| − |10|?",
      choices: ["−7", "−13", "13"],
      correct: "−7",
    },
    {
      level: 8,
      vars: { ctx: "sub", k: 2, v: "B", s: -12, m1: -6, m2: 10 },
      prompt:
        "A submarine is at −12 m. It dives 6 m, then rises 10 m. What is the depth now?",
      choices: ["−8 m", "−28 m", "−18 m"],
      correct: "−8 m",
    },
    {
      level: 8,
      vars: { ctx: "bank", k: 2, v: "B", s: -5, m1: 20, m2: -9, N: "Mia" },
      prompt:
        "Mia's balance is −$5. Mia pays in $20, then spends $9. What is the balance now?",
      choices: ["$6", "−$34", "$24"],
      correct: "$6",
    },
    {
      level: 8,
      vars: { ctx: "temp", k: 3, v: "A", s: -20, m1: 6, m2: 4, m3: -15 },
      prompt:
        "The temperature is −20 °C. It rises 6°, then rises 4°, then drops 15°. What is the temperature now?",
      choices: ["−25 °C", "5 °C", "−10 °C"],
      correct: "−25 °C",
    },
    {
      level: 8,
      vars: { ctx: "temp", k: 3, v: "A", s: -3, m1: -4, m2: -2, m3: 12 },
      prompt:
        "The temperature is −3 °C. It drops 4°, then drops 2°, then rises 12°. What is the temperature now?",
      choices: ["3 °C", "15 °C", "−21 °C"],
      correct: "3 °C",
    },
    {
      level: 9,
      vars: { star: "R", o1: "−", o3: "−", a: 12, b: 2, c: 9, d: 4 },
      prompt: "Which brackets make 12 − 2 × 9 − 4 equal 2?",
      choices: ["12 − 2 × (9 − 4)", "(12 − 2) × 9 − 4", "12 − (2 × 9) − 4"],
      correct: "12 − 2 × (9 − 4)",
    },
    {
      level: 9,
      vars: { star: "L", o1: "+", o3: "+", a: 3, b: 5, c: 2, d: 7 },
      prompt: "Which brackets make 3 + 5 × 2 + 7 equal 23?",
      choices: ["(3 + 5) × 2 + 7", "3 + 5 × (2 + 7)", "3 + (5 × 2) + 7"],
      correct: "(3 + 5) × 2 + 7",
    },
    {
      level: 10,
      vars: { form: "N", a: -6, b: 2, c: 5, d: 4, e: 3 },
      prompt: "What is −6 − [2 − (5 − 4)] × (−3)?",
      choices: ["−3", "−27", "−9"],
      correct: "−3",
    },
  ],
} satisfies Examples;
