import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { a: 3, b: 2, v: 4 },
      { a: 5, b: -3, v: -2 },
      { a: 2, b: 7, v: 6 },
    ],
    2: [
      { form: "S", m: 2, k: 5 },
      { form: "G", m: 4, k: 3 },
      { form: "Q", m: 5, k: 2 },
    ],
    3: [
      { v: "X", a: 3, b: 5, c: 2, d: -1 },
      { v: "C", a: 4, b: -7, c: -1, d: 2 },
      { v: "X", a: 2, b: 9, c: 6, d: -4 },
    ],
    4: [
      { v: "A", m: 3, a: 2, b: 4 },
      { v: "B", m: -2, a: 1, b: -5 },
      { v: "A", m: 5, a: 3, b: -2 },
    ],
    5: [
      { form: "A", a: 7, x: 5 },
      { form: "M", a: 4, x: -6 },
      { form: "D", a: 3, b: 6 },
    ],
    6: [
      { a: 3, b: 6, x: 5 },
      { a: 4, b: -6, x: 7 },
      { a: 5, b: 10, x: -3 },
    ],
    7: [
      { a: 5, c: 2, b: -3, x: 4 },
      { a: 2, c: 6, b: 2, x: 3 },
      { a: 3, c: 1, b: -6, x: -3 },
    ],
    8: [
      {
        form: "V",
        context: "P",
        s: "F",
        n: 4,
        f: 8,
        u: 9,
        Name: "Ava",
        item: "cinema tickets",
      },
      {
        form: "Q",
        context: "R",
        s: "F",
        n: 3,
        f: 12,
        u: 9,
        Name: "Ava",
        rate: "taxi",
      },
      {
        form: "V",
        context: "P",
        s: "D",
        n: 5,
        f: 10,
        u: 12,
        Name: "Ava",
        item: "cinema tickets",
      },
    ],
    9: [
      { m: 3, b: -3, c: 4, x: 7 },
      { m: 2, b: 6, c: -5, x: 4 },
      { m: 4, b: -4, c: 5, x: -2 },
    ],
    10: [
      { form: "N", k: 3, kind: "whole", which: "largest", m: 16 },
      { form: "N", k: 3, kind: "even", which: "smallest", m: 14 },
      {
        form: "A",
        dir: "future",
        who: "younger",
        d: 6,
        k: 4,
        y: 13,
        P: "Ava",
        Q: "Ben",
      },
    ],
  },
  extra: [
    {
      level: 2,
      vars: { form: "T", m: 3, k: 7 },
      prompt: 'Which expression means "7 more than 3 times a number n"?',
      choices: ["3n + 7", "3(n + 7)", "7n + 3"],
      correct: "3n + 7",
    },
    {
      level: 3,
      vars: { v: "C", a: 3, b: 2, c: 3, d: 5 },
      prompt: "Simplify 3x + 2 + 3x + 5.",
      choices: ["6x + 7", "6x − 3", "6x + 2"],
      correct: "6x + 7",
    },
    {
      level: 3,
      vars: { v: "C", a: 1, b: -9, c: 1, d: -4 },
      prompt: "Simplify x − 9 + x − 4.",
      choices: ["2x − 13", "2x − 5", "2x − 9"],
      correct: "2x − 13",
    },
    {
      level: 3,
      vars: { v: "C", a: 4, b: -7, c: 4, d: 2 },
      prompt: "Simplify 4x − 7 + 4x + 2.",
      choices: ["8x − 5", "8x − 9", "8x − 7"],
      correct: "8x − 5",
    },
    {
      level: 3,
      vars: { v: "X", a: 5, b: 3, c: 4, d: -8 },
      prompt: "Simplify 5x + 3 + 4x − 8.",
      choices: ["9x − 5", "x − 5", "20x − 5"],
      correct: "9x − 5",
    },
    {
      level: 3,
      vars: { v: "X", a: 1, b: 3, c: 5, d: -8 },
      prompt: "Simplify x + 3 + 5x − 8.",
      choices: ["6x − 5", "−4x − 5", "5x − 5"],
      correct: "6x − 5",
    },
    {
      level: 3,
      vars: { v: "C", a: 1, b: -4, c: -3, d: -2 },
      prompt: "Simplify x − 4 − 3x − 2.",
      choices: ["−2x − 6", "−2x − 2", "−2x − 4"],
      correct: "−2x − 6",
    },
    {
      level: 4,
      vars: { v: "A", m: -3, a: 2, b: 4 },
      prompt: "Expand −3(2x + 4).",
      choices: ["−6x − 12", "−6x + 4", "−6x + 12"],
      correct: "−6x − 12",
    },
    {
      level: 4,
      vars: { v: "B", m: 4, a: 3, b: -1 },
      prompt: "Expand 4(3x − 1).",
      choices: ["12x − 4", "−12x − 4", "3x − 4"],
      correct: "12x − 4",
    },
    {
      level: 5,
      vars: { form: "A", a: -7, x: 19 },
      prompt: "Solve x − 7 = 12.",
      choices: ["x = 19", "x = 5", "x = −19"],
      correct: "x = 19",
    },
    {
      level: 7,
      vars: { a: 1, c: 5, b: 4, x: -2 },
      prompt: "Solve x + 4 = 5x + 12.",
      choices: ["x = −2", "x = −4", "x = 8"],
      correct: "x = −2",
    },
    {
      level: 8,
      vars: {
        form: "V",
        context: "R",
        s: "F",
        n: 6,
        f: 12,
        u: 5,
        Name: "Leo",
        rate: "plumber",
      },
      prompt:
        "A plumber charges a $12 call-out fee plus $6 an hour. Leo paid $42 in total. How many hours was the job?",
      choices: ["5 hours", "9 hours", "30 hours"],
      correct: "5 hours",
    },
    {
      level: 8,
      vars: {
        form: "V",
        context: "R",
        s: "F",
        n: 4,
        f: 8,
        u: 10,
        Name: "Sam",
        rate: "taxi",
      },
      prompt:
        "A taxi charges an $8 pick-up fee plus $4 per km. Sam paid $48 in total. How many km was the ride?",
      choices: ["10 km", "14 km", "40 km"],
      correct: "10 km",
    },
    {
      level: 8,
      vars: {
        form: "V",
        context: "R",
        s: "D",
        n: 2,
        f: 6,
        u: 9,
        Name: "Mia",
        rate: "taxi",
      },
      prompt:
        "A taxi charges $2 per km and takes $6 off for members. Mia paid $12 in total. How many km was the ride?",
      choices: ["9 km", "3 km", "18 km"],
      correct: "9 km",
    },
    {
      level: 8,
      vars: {
        form: "V",
        context: "R",
        s: "D",
        n: 4,
        f: 8,
        u: 5,
        Name: "Noor",
        rate: "plumber",
      },
      prompt:
        "A plumber charges $4 an hour and takes $8 off for members. Noor paid $12 in total. How many hours was the job?",
      choices: ["5 hours", "1 hour", "20 hours"],
      correct: "5 hours",
    },
    {
      level: 8,
      vars: {
        form: "V",
        context: "P",
        s: "F",
        n: 6,
        f: 18,
        u: 4,
        Name: "Pia",
        item: "badges",
      },
      prompt:
        "Pia buys 6 badges and pays an $18 postage charge. The total is $42. What does one badge cost?",
      choices: ["$4", "$10", "$24"],
      correct: "$4",
    },
    {
      level: 8,
      vars: {
        form: "V",
        context: "P",
        s: "D",
        n: 2,
        f: 4,
        u: 15,
        Name: "Kai",
        item: "plant pots",
      },
      prompt:
        "Kai buys 2 plant pots and uses a $4 voucher. The total is $26. What does one plant pot cost?",
      choices: ["$15", "$11", "$30"],
      correct: "$15",
    },
    {
      level: 8,
      vars: {
        form: "Q",
        context: "P",
        s: "F",
        n: 3,
        f: 18,
        u: 7,
        Name: "Omar",
        item: "T-shirts",
      },
      prompt:
        "Omar buys 3 T-shirts and pays an $18 delivery charge. The total is $39. Which equation gives the price x of one T-shirt?",
      choices: ["3x + 18 = 39", "3(x + 18) = 39", "18x + 3 = 39"],
      correct: "3x + 18 = 39",
    },
    {
      level: 8,
      vars: {
        form: "Q",
        context: "P",
        s: "F",
        n: 7,
        f: 14,
        u: 3,
        Name: "Eli",
        item: "notebooks",
      },
      prompt:
        "Eli buys 7 notebooks and pays a $14 delivery charge. The total is $35. Which equation gives the price x of one notebook?",
      choices: ["7x + 14 = 35", "7(x + 14) = 35", "14x + 7 = 35"],
      correct: "7x + 14 = 35",
    },
    {
      level: 8,
      vars: {
        form: "Q",
        context: "P",
        s: "D",
        n: 4,
        f: 12,
        u: 9,
        Name: "Zoe",
        item: "comic books",
      },
      prompt:
        "Zoe buys 4 comic books and uses a $12 voucher. The total is $24. Which equation gives the price x of one comic book?",
      choices: ["4x − 12 = 24", "4(x − 12) = 24", "12x − 4 = 24"],
      correct: "4x − 12 = 24",
    },
    {
      level: 8,
      vars: {
        form: "Q",
        context: "R",
        s: "D",
        n: 5,
        f: 15,
        u: 8,
        Name: "Raj",
        rate: "plumber",
      },
      prompt:
        "A plumber charges $5 an hour and takes $15 off for members. Raj paid $25 in total. Which equation gives the number of hours x?",
      choices: ["5x − 15 = 25", "5(x − 15) = 25", "15x − 5 = 25"],
      correct: "5x − 15 = 25",
    },
    {
      level: 10,
      vars: { form: "N", k: 5, kind: "odd", which: "largest", m: 21 },
      prompt: "Five consecutive odd numbers add up to 105. What is the largest?",
      choices: ["25", "21", "23"],
      correct: "25",
    },
    {
      level: 10,
      vars: { form: "N", k: 5, kind: "whole", which: "smallest", m: 30 },
      prompt:
        "Five consecutive whole numbers add up to 150. What is the smallest?",
      choices: ["28", "30", "26"],
      correct: "28",
    },
    {
      level: 10,
      vars: {
        form: "A",
        dir: "past",
        who: "older",
        d: 3,
        k: 6,
        y: 10,
        P: "Uma",
        Q: "Sam",
      },
      prompt:
        "Uma is 3 years older than Sam. 6 years ago their ages added up to 11. How old is Uma now?",
      choices: ["13", "7", "10"],
      correct: "13",
    },
    {
      level: 10,
      vars: {
        form: "A",
        dir: "future",
        who: "older",
        d: 5,
        k: 2,
        y: 8,
        P: "Fay",
        Q: "Gus",
      },
      prompt:
        "Fay is 5 years older than Gus. In 2 years their ages will add up to 25. How old is Fay now?",
      choices: ["13", "15", "14"],
      correct: "13",
    },
    {
      level: 10,
      vars: {
        form: "A",
        dir: "past",
        who: "younger",
        d: 4,
        k: 10,
        y: 12,
        P: "Jo",
        Q: "Ivy",
      },
      prompt:
        "Jo is 4 years older than Ivy. 10 years ago their ages added up to 8. How old is Ivy now?",
      choices: ["12", "2", "7"],
      correct: "12",
    },
  ],
} satisfies Examples;
