import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { form: "F", a: 8, q: 2, b: 5 },
      { form: "F", a: 5, q: -7, b: -2 },
      { form: "D", k: 2, w: 3, b: -10 },
    ],
    2: [
      { form: "W", i: 10 },
      { form: "W", i: 1 },
      { form: "N", a: 2, b: 3, c: 6 },
    ],
    3: [
      { v: "R", a: -6, rel: ">", n: -2, b: 3 },
      { v: "V", a: -8, rel: "≤", n: 9, b: -20 },
      { v: "V", a: 7, rel: "<", n: -7, b: -14 },
    ],
    4: [
      { a: 5, b: 15, lo: -6, hi: 3, r1: "<", r2: "≤" },
      { a: 4, b: -10, lo: 2, hi: 9, r1: "≤", r2: "≤" },
      { a: 3, b: 15, lo: 4, hi: 7, r1: "<", r2: "<" },
    ],
    5: [
      { s: "P", a: 5, p: 6, q: 3 },
      { s: "Z", a: 2, p: 8, q: 5 },
      { s: "P", a: 4, p: 7, q: 1 },
    ],
    6: [
      { op: "A", a: 3, c: 5, x: 4, y: -5 },
      { op: "B", a: 1, c: 5, x: -3, y: 6 },
      { op: "A", a: 1, c: 4, x: 6, y: -6 },
    ],
    7: [
      { form: "E", case: "inf", m: 6, e: 2, f: 3 },
      { form: "E", case: "none", m: 4, e: 2, f: -1, b: 18 },
      { form: "S", case: "one", a: 1, b: -2, c: -4, d: 1, e: -1, f: -3 },
    ],
    8: [
      {
        s: "max",
        u: "U",
        r: 250,
        f: 15,
        T: 53,
        context: "fair",
        Name: "Fay",
      },
      {
        s: "min",
        u: "I",
        r: 350,
        f: 19,
        T: 84,
        context: "team",
        Name: "Ava",
      },
      {
        s: "max",
        u: "I",
        r: 150,
        f: 17,
        T: 66,
        context: "day out",
        Name: "Mia",
      },
    ],
    9: [
      {
        which: "A",
        t: "hi",
        pC: 6,
        g: 3,
        N: 20,
        A: 6,
        context: "show",
        Name: "Noor",
      },
      {
        which: "C",
        t: "lo",
        pC: 3,
        g: 3,
        N: 21,
        A: 18,
        context: "show",
        Name: "Tia",
      },
      {
        which: "A",
        t: "lo",
        pC: 5,
        g: 5,
        N: 23,
        A: 4,
        context: "café",
        Name: "Zoe",
      },
    ],
    10: [
      { v: "K", d: "LT", st: "strict", a: 2, p: 2, q: 5 },
      { v: "K", d: "GT", st: "loose", a: 4, p: 1, q: 2 },
      { v: "V", d: "LT", st: "loose", a: 3, p: -8, q: 2 },
    ],
  },
  extra: [
    {
      level: 1,
      vars: { form: "D", k: 4, w: 2, b: 3 },
      prompt: "Solve 0.25x + 3 = 11.",
      choices: ["32", "2", "56"],
      correct: "32",
    },
    {
      level: 1,
      vars: { form: "D", k: 5, w: -3, b: 7 },
      prompt: "Solve 0.2x + 7 = −8.",
      choices: ["−75", "−3", "−5"],
      correct: "−75",
    },
    {
      level: 2,
      vars: { form: "W", i: 2 },
      prompt: "A = ½bh. Solve for b.",
      choices: ["b = 2A/h", "b = A/(2h)", "b = A/h"],
      correct: "b = 2A/h",
    },
    {
      level: 2,
      vars: { form: "W", i: 3 },
      prompt: "P = 2(l + w). Solve for w.",
      choices: ["w = P/2 − l", "w = (P − l)/2", "w = P/2 + l"],
      correct: "w = P/2 − l",
    },
    {
      level: 2,
      vars: { form: "W", i: 4 },
      prompt: "P = 2(l + w). Solve for l.",
      choices: ["l = P/2 − w", "l = (P − w)/2", "l = P/2 + w"],
      correct: "l = P/2 − w",
    },
    {
      level: 2,
      vars: { form: "W", i: 5 },
      prompt: "d = rt. Solve for t.",
      choices: ["t = d/r", "t = d·r", "t = r/d"],
      correct: "t = d/r",
    },
    {
      level: 2,
      vars: { form: "W", i: 6 },
      prompt: "d = rt. Solve for r.",
      choices: ["r = d/t", "r = d·t", "r = t/d"],
      correct: "r = d/t",
    },
    {
      level: 2,
      vars: { form: "W", i: 7 },
      prompt: "F = 9/5·C + 32. Solve for C.",
      choices: ["C = 5(F − 32)/9", "C = 5F/9 − 32", "C = 9(F − 32)/5"],
      correct: "C = 5(F − 32)/9",
    },
    {
      level: 2,
      vars: { form: "W", i: 8 },
      prompt: "I = Prt. Solve for r.",
      choices: ["r = I/(Pt)", "r = It/P", "r = I/(P + t)"],
      correct: "r = I/(Pt)",
    },
    {
      level: 2,
      vars: { form: "W", i: 9 },
      prompt: "y = mx + b. Solve for x.",
      choices: ["x = (y − b)/m", "x = y/m − b", "x = (y + b)/m"],
      correct: "x = (y − b)/m",
    },
    {
      level: 2,
      vars: { form: "W", i: 11 },
      prompt: "E = mc². Solve for m.",
      choices: ["m = E/c²", "m = E/(2c)", "m = Ec²"],
      correct: "m = E/c²",
    },
    {
      level: 2,
      vars: { form: "W", i: 12 },
      prompt: "A = ½(a + b)h. Solve for h.",
      choices: ["h = 2A/(a + b)", "h = A/(2(a + b))", "h = 2A/(ab)"],
      correct: "h = 2A/(a + b)",
    },
    {
      level: 2,
      vars: { form: "W", i: 13 },
      prompt: "C = 2πr. Solve for r.",
      choices: ["r = C/(2π)", "r = 2C/π", "r = 2πC"],
      correct: "r = C/(2π)",
    },
    {
      level: 2,
      vars: { form: "W", i: 14 },
      prompt: "V = lwh. Solve for h.",
      choices: ["h = V/(lw)", "h = Vw/l", "h = V/(l + w)"],
      correct: "h = V/(lw)",
    },
    {
      level: 2,
      vars: { form: "N", a: 4, b: 6, c: -9 },
      prompt: "Solve 4x + 6y = −9 for y.",
      choices: ["y = (−9 − 4x)/6", "y = −9/6 − 4x", "y = (−9 + 4x)/6"],
      correct: "y = (−9 − 4x)/6",
    },
    {
      level: 5,
      vars: { s: "P", a: 2, p: -5, q: 2 },
      prompt: "Solve |2x + 10| = 4.",
      choices: ["x = −7 or x = −3", "x = 3 or x = 7", "no solution"],
      correct: "x = −7 or x = −3",
    },
    {
      level: 5,
      vars: { s: "P", a: 3, p: 5, q: 4 },
      prompt: "Solve |3x − 15| = 12.",
      choices: ["x = 1 or x = 9", "x = −9 or x = −1", "no solution"],
      correct: "x = 1 or x = 9",
    },
    {
      level: 5,
      vars: { s: "P", a: 2, p: -7, q: 6 },
      prompt: "Solve |2x + 14| = 12.",
      choices: ["x = −13 or x = −1", "x = 1 or x = 13", "no solution"],
      correct: "x = −13 or x = −1",
    },
    {
      level: 5,
      vars: { s: "P", a: 3, p: 2, q: 5 },
      prompt: "Solve |3x − 6| = 15.",
      choices: ["x = −3 or x = 7", "x = −7 or x = 3", "no solution"],
      correct: "x = −3 or x = 7",
    },
    {
      level: 5,
      vars: { s: "P", a: 2, p: -3, q: 9 },
      prompt: "Solve |2x + 6| = 18.",
      choices: ["x = −12 or x = 6", "x = −6 or x = 12", "no solution"],
      correct: "x = −12 or x = 6",
    },
    {
      level: 5,
      vars: { s: "Z", a: 3, p: 4, q: 4 },
      prompt: "Solve |3x − 12| = −12.",
      choices: ["no solution", "x = 0 or x = 8", "x = −8 or x = 0"],
      correct: "no solution",
    },
    {
      level: 5,
      vars: { s: "P", a: 3, p: 4, q: 4 },
      prompt: "Solve |3x − 12| = 12.",
      choices: ["x = 0 or x = 8", "x = −8 or x = 0", "no solution"],
      correct: "x = 0 or x = 8",
    },
    {
      level: 5,
      vars: { s: "P", a: 2, p: -5, q: 5 },
      prompt: "Solve |2x + 10| = 10.",
      choices: ["x = −10 or x = 0", "x = 0 or x = 10", "no solution"],
      correct: "x = −10 or x = 0",
    },
    {
      level: 5,
      vars: { s: "Z", a: 4, p: -3, q: 3 },
      prompt: "Solve |4x + 12| = −12.",
      choices: ["no solution", "x = −6 or x = 0", "x = 0 or x = 6"],
      correct: "no solution",
    },
    {
      level: 7,
      vars: { form: "E", case: "one", m: 3, e: 2, f: 4, a: 5, b: -7 },
      prompt: "How many solutions does 5x − 7 = 3(2x + 4) have?",
      choices: ["one solution", "no solutions", "infinitely many solutions"],
      correct: "one solution",
    },
    {
      level: 7,
      vars: { form: "S", case: "inf", a: 2, b: -3, c: 5, k: -2 },
      prompt:
        "How many solutions does this system have? 2x − 3y = 5; −4x + 6y = −10.",
      choices: ["one solution", "no solutions", "infinitely many solutions"],
      correct: "infinitely many solutions",
    },
    {
      level: 7,
      vars: { form: "S", case: "none", a: 1, b: 4, c: -6, k: 3, offset: 2 },
      prompt:
        "How many solutions does this system have? x + 4y = −6; 3x + 12y = −16.",
      choices: ["one solution", "no solutions", "infinitely many solutions"],
      correct: "no solutions",
    },
    {
      level: 8,
      vars: {
        s: "min",
        u: "U",
        r: 400,
        f: 7,
        T: 50,
        context: "club",
        Name: "Ben",
      },
      prompt:
        "Ben's club must raise $50. Each raffle ticket sells for $4 and the printing cost $7. What is the fewest tickets they must sell?",
      choices: ["15", "14", "20"],
      correct: "15",
    },
    {
      level: 8,
      vars: {
        s: "max",
        u: "I",
        r: 300,
        f: 9,
        T: 40,
        context: "fair",
        Name: "Leo",
      },
      prompt:
        "Leo has $40. Entry to the fair costs $9 and each ride costs $3. What is the greatest number of rides Leo can take?",
      choices: ["10", "11", "13"],
      correct: "10",
    },
    {
      level: 9,
      vars: {
        which: "C",
        t: "hi",
        pC: 4,
        g: 3,
        N: 18,
        A: 5,
        context: "café",
        Name: "Kai",
      },
      prompt:
        "Kai orders 18 drinks. A large costs $7 and a small costs $4. The bill is $87. How many small drinks were ordered?",
      choices: ["13", "5", "3"],
      correct: "13",
    },
    {
      level: 10,
      vars: { v: "V", d: "GT", st: "strict", a: 2, p: 3, q: 2 },
      prompt: "Solve |2x − 6| > 4.",
      choices: ["x < 1 or x > 5", "x < −5 or x > −1", "x < 4 or x > 8"],
      correct: "x < 1 or x > 5",
    },
    {
      level: 10,
      vars: { v: "V", d: "LT", st: "strict", a: 3, p: -2, q: 4 },
      prompt: "Solve |3x + 6| < 12.",
      choices: ["−6 < x < 2", "−2 < x < 6", "−10 < x < −2"],
      correct: "−6 < x < 2",
    },
    {
      level: 10,
      vars: { v: "K", d: "LT", st: "loose", a: 1, p: -3, q: 4 },
      prompt: "Solve |x + 3| ≤ 4.",
      choices: ["−7 ≤ x ≤ 1", "x ≤ −7 or x ≥ 1", "x ≤ 1"],
      correct: "−7 ≤ x ≤ 1",
    },
  ],
} satisfies Examples;
