import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { form: "Q", s: "hv", x: -4, y: -3 },
      { form: "Q", s: "vd", x: -1, y: 5 },
      { form: "A", ax: "x", x: 7 },
    ],
    2: [
      {
        w: "x",
        o: "up-down first",
        x: -7,
        y: -2,
        a: 8,
        b: 9,
        h: "right",
        v: "down",
      },
      {
        w: "y",
        o: "across first",
        x: 2,
        y: 8,
        a: 10,
        b: 9,
        h: "right",
        v: "up",
      },
      {
        w: "x",
        o: "across first",
        x: -7,
        y: -6,
        a: 4,
        b: 5,
        h: "right",
        v: "up",
      },
    ],
    3: [
      { ax: "H", u: 1, p: -10, q: -8, r: -7 },
      { ax: "V", u: -1, p: -4, q: 10, r: 3 },
      { ax: "H", u: -1, p: -2, q: 1, r: 5 },
    ],
    4: [
      { x1: 6, y1: 7, x2: 2, y2: -2 },
      { x1: 2, y1: 7, x2: -1, y2: -8 },
      { x1: -2, y1: -7, x2: -6, y2: -6 },
    ],
    5: [
      { orbit: 1, q: 7, p: -5, k: 1, d: 1, x1: 3, y1: -2 },
      { orbit: 2, q: 6, p: -7, k: 1, d: -1, x1: -3, y1: 1 },
      { orbit: 1, q: 2, p: -9, k: 2, d: -1, x1: 6, y1: -8 },
    ],
    6: [
      { form: "S", kind: "fraction", orbit: 2, m: [1, 4], b: [-5, 3] },
      { form: "I", kind: "fraction", orbit: 2, m: [-10, 3], b: [-1, 4] },
      { form: "W", kind: "whole", m: 3, b: -2 },
    ],
    7: [
      { m: 3, b: -7, t1: -2, t2: 6, t3: -4 },
      { m: -5, b: 1, t1: 3, t2: 0, t3: 5 },
      { m: 4, b: 8, t1: 3, t2: 0, t3: 5 },
    ],
    8: [
      { orbit: 2, m: -4, dx: 5, x1: 3, y1: 10 },
      { orbit: 2, m: 3, dx: 4, x1: -5, y1: -4 },
      { orbit: 2, m: 4, dx: 4, x1: -2, y1: -10 },
    ],
    9: [
      {
        form: "T",
        z: "sum,square",
        legs: [8, 15],
        sx: -1,
        sy: 1,
        x1: 5,
        y1: -6,
      },
      { form: "R", z: "long", legs: [7, 1], sx: -1, sy: 1, x1: 10, y1: -4 },
      {
        form: "T",
        z: "long,diff",
        legs: [12, 9],
        sx: 1,
        sy: -1,
        x1: -3,
        y1: 10,
      },
    ],
    10: [
      { form: "par", orbit: 2, ab: [3, 2], sa: -1, sp: -1, q: 0, c: 5 },
      { form: "perp", orbit: 1, ab: [2, 5], sa: 1, sp: 1, q: -10, c: 7 },
      { form: "perp", orbit: 2, ab: [4, 3], sa: -1, sp: 1, q: 2, c: 5 },
    ],
  },
  extra: [
    {
      level: 1,
      vars: { form: "A", ax: "y", y: -4 },
      prompt: "Where does the point (0, −4) lie?",
      choices: ["on the y-axis", "on the x-axis", "Quadrant IV"],
      correct: "on the y-axis",
    },
    {
      level: 1,
      vars: { form: "A", ax: "x", x: -6 },
      prompt: "Where does the point (−6, 0) lie?",
      choices: ["on the x-axis", "on the y-axis", "Quadrant II"],
      correct: "on the x-axis",
    },
    {
      level: 1,
      vars: { form: "Q", s: "hd", x: 3, y: 5 },
      prompt: "Where does the point (3, 5) lie?",
      choices: ["Quadrant I", "Quadrant II", "Quadrant III"],
      correct: "Quadrant I",
    },
    {
      level: 2,
      vars: {
        w: "y",
        o: "across first",
        x: 3,
        y: -4,
        a: 6,
        b: 2,
        h: "left",
        v: "down",
      },
      prompt: "Start at (3, −4). Move 6 left and 2 down. Where do you land?",
      choices: ["(−3, −6)", "(−3, −2)", "(1, −10)"],
      correct: "(−3, −6)",
    },
    {
      level: 2,
      vars: {
        w: "x",
        o: "up-down first",
        x: 5,
        y: 1,
        a: 7,
        b: 3,
        h: "left",
        v: "up",
      },
      prompt: "Start at (5, 1). Move 3 up and 7 left. Where do you land?",
      choices: ["(−2, 4)", "(12, 4)", "(8, −6)"],
      correct: "(−2, 4)",
    },
    {
      level: 5,
      vars: { orbit: 2, q: 4, p: 3, k: 2, d: 1, x1: -5, y1: -1 },
      prompt: "What is the slope of the line through (−5, −1) and (3, 5)?",
      choices: ["3/4", "4/3", "−3/4"],
      correct: "3/4",
    },
    {
      level: 5,
      vars: { orbit: 1, q: 2, p: 5, k: 1, d: -1, x1: 4, y1: 3 },
      prompt: "What is the slope of the line through (4, 3) and (2, −2)?",
      choices: ["5/2", "2/5", "−2/5"],
      correct: "5/2",
    },
    {
      level: 6,
      vars: { form: "S", kind: "whole", orbit: 1, m: 1, b: -3 },
      prompt: "In y = x − 3, what is the slope?",
      choices: ["1", "−3", "3"],
      correct: "1",
    },
    {
      level: 6,
      vars: { form: "I", kind: "whole", orbit: 1, m: -1, b: 4 },
      prompt: "In y = −x + 4, what is the y-intercept?",
      choices: ["4", "−1", "1"],
      correct: "4",
    },
    {
      level: 6,
      vars: { form: "I", kind: "whole", orbit: 2, m: 2, b: -5 },
      prompt: "In y = 2x − 5, what is the y-intercept?",
      choices: ["−5", "5", "−2"],
      correct: "−5",
    },
    {
      level: 6,
      vars: { form: "S", kind: "fraction", orbit: 1, m: [7, 2], b: [4, 3] },
      prompt: "In y = (7/2)x + 4/3, what is the slope?",
      choices: ["7/2", "4/3", "−4/3"],
      correct: "7/2",
    },
    {
      level: 6,
      vars: { form: "W", kind: "fraction", m: [-5, 3], b: [1, 4] },
      prompt:
        "A line has slope −5/3 and y-intercept 1/4. Which equation is it?",
      choices: ["y = (−5/3)x + 1/4", "y = (1/4)x − 5/3", "y = (−5/3)(x + 1/4)"],
      correct: "y = (−5/3)x + 1/4",
    },
    {
      level: 6,
      vars: { form: "W", kind: "whole", m: -1, b: 4 },
      prompt: "A line has slope −1 and y-intercept 4. Which equation is it?",
      choices: ["y = −x + 4", "y = 4x − 1", "y = −(x + 4)"],
      correct: "y = −x + 4",
    },
    {
      level: 6,
      vars: { form: "W", kind: "whole", m: 2, b: -1 },
      prompt: "A line has slope 2 and y-intercept −1. Which equation is it?",
      choices: ["y = 2x − 1", "y = −x + 2", "y = 2(x − 1)"],
      correct: "y = 2x − 1",
    },
    {
      level: 7,
      vars: { m: -1, b: 2, t1: 4, t2: -3, t3: 2 },
      prompt: "Which point lies on y = −x + 2?",
      choices: ["(4, −2)", "(−3, 1)", "(2, 3)"],
      correct: "(4, −2)",
    },
    {
      level: 7,
      vars: { m: 1, b: -6, t1: 2, t2: 5, t3: -2 },
      prompt: "Which point lies on y = x − 6?",
      choices: ["(2, −4)", "(5, 11)", "(−2, 13)"],
      correct: "(2, −4)",
    },
    {
      level: 8,
      vars: { orbit: 1, m: 2, dx: -3, x1: 4, y1: 5 },
      prompt: "Which equation describes the line through (4, 5) and (1, −1)?",
      choices: ["y = 2x − 3", "y = −6x + 29", "y = 6x − 19"],
      correct: "y = 2x − 3",
    },
    {
      level: 8,
      vars: { orbit: 2, m: -1, dx: -2, x1: 3, y1: -4 },
      prompt: "Which equation describes the line through (3, −4) and (1, −2)?",
      choices: ["y = −x − 1", "y = x − 7", "y = −2x + 2"],
      correct: "y = −x − 1",
    },
    {
      level: 8,
      vars: { orbit: 1, m: 1, dx: 2, x1: -3, y1: 5 },
      prompt: "Which equation describes the line through (−3, 5) and (−1, 7)?",
      choices: ["y = x + 8", "y = 2x + 11", "y = −2x − 1"],
      correct: "y = x + 8",
    },
    {
      level: 9,
      vars: {
        form: "T",
        z: "sum,long",
        legs: [6, 8],
        sx: 1,
        sy: 1,
        x1: -4,
        y1: 1,
      },
      prompt: "How far is it from (−4, 1) to (2, 9)?",
      choices: ["10", "14", "8"],
      correct: "10",
    },
    {
      level: 9,
      vars: { form: "R", z: "sum", legs: [2, 4], sx: -1, sy: -1, x1: 1, y1: 0 },
      prompt: "How far is it from (1, 0) to (−1, −4)?",
      choices: ["2√5", "5√2", "6"],
      correct: "2√5",
    },
    {
      level: 9,
      vars: {
        form: "R",
        z: "square",
        legs: [3, 6],
        sx: 1,
        sy: -1,
        x1: -2,
        y1: 7,
      },
      prompt: "How far is it from (−2, 7) to (1, 1)?",
      choices: ["3√5", "5√3", "45"],
      correct: "3√5",
    },
    {
      level: 10,
      vars: { form: "par", orbit: 1, ab: [2, 5], sa: 1, sp: -1, q: 3, c: -4 },
      prompt:
        "Which line is parallel to y = (2/5)x − 4 and passes through (−10, 3)?",
      choices: ["y = (2/5)x + 7", "y = (5/2)x + 28", "y = (−5/2)x − 22"],
      correct: "y = (2/5)x + 7",
    },
    {
      level: 10,
      vars: { form: "perp", orbit: 1, ab: [3, 4], sa: 1, sp: 1, q: -5, c: 2 },
      prompt:
        "Which line is perpendicular to y = (3/4)x + 2 and passes through (12, −5)?",
      choices: ["y = (−4/3)x + 11", "y = (−3/4)x + 4", "y = (3/4)x − 14"],
      correct: "y = (−4/3)x + 11",
    },
  ],
} satisfies Examples;
