import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { w: "med", u: "drop", n: 3, v1: 17, v2: 11, v3: 8, j: 3 },
      { w: "mid", u: "tot", n: 3, v1: 12, v2: 16, v3: 2 },
      { w: "mid", u: "drop", n: 5, v1: 2, v2: 12, v3: 16, v4: 2, v5: 3, j: 5 },
    ],
    2: [
      {
        form: "M",
        n: 6,
        pair: "late",
        v1: 9,
        v2: 15,
        v3: 3,
        v4: 7,
        v5: 19,
        v6: 7,
      },
      { form: "O", m: 15, p: 13, q: 20, list: [15, 13, 15, 15, 13, 20, 20] },
      { form: "R", sw: "B", n: 6, v1: 10, v2: 12, v3: 10, v4: 14, v5: 2, v6: 11 },
    ],
    3: [
      { z: "other-one", bag: "discs", r: 2, b: 10, ca: "green" },
      { z: "other-less", bag: "counters", r: 11, b: 3, ca: "green" },
      { z: "part-less", bag: "tiles", r: 7, b: 5, ca: "white" },
    ],
    4: [
      {
        form: "C",
        z: "self-cols",
        k: 4,
        colours: ["blue", "green", "red", "yellow", "white"],
        c1: 3,
        c2: 7,
        c3: 8,
        c4: 1,
        i: 3,
      },
      { form: "X", T: 6, fam: "less", answer: "0" },
      { form: "X", T: 15, fam: "less", answer: "1" },
    ],
    5: [
      { w: "km", N: 5, M: 14, v1: 11, v2: 13, v3: 14, v4: 14, Name: "Ava" },
      { w: "sh", N: 5, M: 8, v1: 4, v2: 3, v3: 3, v4: 13, Name: "Mia" },
      {
        w: "fg",
        N: 6,
        M: 10,
        v1: 18,
        v2: 15,
        v3: 4,
        v4: 5,
        v5: 15,
        j: 1,
        Name: "Cleo",
      },
    ],
    6: [
      { z: "add-med", dev1: "die", dev2: "coin", die: "face", v: 6, coin: "tails" },
      {
        z: "one-comp",
        dev1: "die",
        dev2: "spinner",
        die: "parity",
        parity: "odd",
        sections: 8,
        a: 6,
        colour: "red",
      },
      { z: "med-comp", dev1: "coin", dev2: "die", coin: "heads", die: "less", v: 6 },
    ],
    7: [
      { j: 2, z: "all-sum", menu: "cinema", c1: 6, c2: 6, c3: 5, i: 1 },
      { j: 2, z: "swap-drop", menu: "stall", c1: 2, c2: 5, c3: 6, i: 2 },
      { j: 3, z: "sum-drop", menu: "shop", c1: 4, c2: 2, c3: 5, c4: 3, i: 1 },
    ],
    8: [
      { z: "rep-den", bag: "discs", r: 3, b: 2, ca: "black" },
      { z: "num-other", bag: "counters", r: 3, b: 5, ca: "green" },
      { z: "den-other", bag: "discs", r: 6, b: 2, ca: "black" },
    ],
    9: [
      { form: "E", z: "den-comp", s: 10, a: 4, n: 70, colour: "green" },
      { form: "E", z: "comp-div", s: 5, a: 3, n: 60, colour: "yellow" },
      { form: "X", s: 10, a: 4, n: 100, k: 26, colour: "green", Name: "Mia" },
    ],
    10: [
      { form: "C", z: "perm-divr", group: "panel", n: 6, r: 4 },
      { form: "P", z: "comb-pow", group: "crew", n: 6, r: 4 },
      { form: "C", z: "mult-addf", group: "club", n: 8, r: 3 },
    ],
  },
  extra: [
    {
      level: 1,
      vars: { w: "med", u: "tot", n: 4, v1: 4, v2: 9, v3: 5, v4: 14 },
      prompt: "What is the mean of 4, 9, 5, 14?",
      choices: ["8", "7", "32"],
      correct: "8",
    },
    {
      level: 1,
      vars: {
        w: "mid",
        u: "drop",
        n: 6,
        v1: 3,
        v2: 8,
        v3: 19,
        v4: 6,
        v5: 1,
        v6: 11,
        j: 1,
      },
      prompt: "What is the mean of 3, 8, 19, 6, 1, 11?",
      choices: ["8", "10", "9"],
      correct: "8",
    },
    {
      level: 2,
      vars: {
        form: "M",
        n: 7,
        sd: "same",
        v1: 12,
        v2: 4,
        v3: 18,
        v4: 6,
        v5: 15,
        v6: 4,
        v7: 10,
      },
      prompt: "What is the median of 12, 4, 18, 6, 15, 4, 10?",
      choices: ["10", "6", "4"],
      correct: "10",
    },
    {
      level: 2,
      vars: { form: "M", n: 5, sd: "split", v1: 16, v2: 11, v3: 8, v4: 3, v5: 16 },
      prompt: "What is the median of 16, 11, 8, 3, 16?",
      choices: ["11", "8", "16"],
      correct: "11",
    },
    {
      level: 2,
      vars: {
        form: "M",
        n: 6,
        pair: "early",
        v1: 20,
        v2: 8,
        v3: 2,
        v4: 12,
        v5: 20,
        v6: 4,
      },
      prompt: "What is the median of 20, 8, 2, 12, 20, 4?",
      choices: ["10", "6", "11"],
      correct: "10",
    },
    {
      level: 2,
      vars: { form: "R", sw: "A", n: 5, v1: 7, v2: 13, v3: 7, v4: 3, v5: 18 },
      prompt: "What is the range of 7, 13, 7, 3, 18?",
      choices: ["15", "18", "16"],
      correct: "15",
    },
    {
      level: 2,
      vars: {
        form: "R",
        sw: "C",
        n: 7,
        v1: 9,
        v2: 5,
        v3: 16,
        v4: 9,
        v5: 12,
        v6: 4,
        v7: 19,
      },
      prompt: "What is the range of 9, 5, 16, 9, 12, 4, 19?",
      choices: ["15", "12", "14"],
      correct: "15",
    },
    {
      level: 3,
      vars: { z: "other-one", bag: "beads", r: 9, b: 4, ca: "white" },
      prompt:
        "A bag holds 9 black beads and 4 white beads. One bead is taken at random. What is the probability that it is white?",
      choices: ["4/13", "9/13", "1/13"],
      correct: "4/13",
    },
    {
      level: 4,
      vars: {
        form: "C",
        z: "self-less",
        k: 3,
        colours: ["green", "white", "red", "blue", "yellow"],
        c1: 4,
        c2: 2,
        c3: 5,
        i: 1,
      },
      prompt:
        "A bag holds 4 green, 2 white and 5 red marbles. One marble is taken at random. What is the probability that it is not green?",
      choices: ["7/11", "4/11", "7/10"],
      correct: "7/11",
    },
    {
      level: 4,
      vars: {
        form: "C",
        z: "cols-less",
        k: 4,
        colours: ["yellow", "red", "white", "green", "blue"],
        c1: 2,
        c2: 3,
        c3: 1,
        c4: 6,
        i: 4,
      },
      prompt:
        "A bag holds 2 yellow, 3 red, 1 white and 6 green marbles. One marble is taken at random. What is the probability that it is not green?",
      choices: ["1/2", "3/4", "6/11"],
      correct: "1/2",
    },
    {
      level: 4,
      vars: { form: "X", T: 8, fam: "greater", answer: "1/T" },
      prompt:
        "A spinner with 8 equal sections numbered 1 to 8 is spun once. What is the probability of a number greater than 7?",
      choices: ["0", "1/8", "1"],
      correct: "1/8",
    },
    {
      level: 4,
      vars: { form: "X", T: 20, fam: "greater", answer: "1" },
      prompt:
        "A spinner with 20 equal sections numbered 1 to 20 is spun once. What is the probability of a number greater than 0?",
      choices: ["0", "1/20", "1"],
      correct: "1",
    },
    {
      level: 4,
      vars: { form: "X", T: 6, fam: "greater", answer: "0" },
      prompt:
        "A fair die is rolled once. What is the probability of a number greater than 6?",
      choices: ["0", "1/6", "1"],
      correct: "0",
    },
    {
      level: 4,
      vars: { form: "X", T: 6, fam: "less", answer: "1/T" },
      prompt:
        "A fair die is rolled once. What is the probability of a number less than 2?",
      choices: ["0", "1/6", "1"],
      correct: "1/6",
    },
    {
      level: 5,
      vars: { w: "sh", N: 4, M: 11, v1: 9, v2: 12, v3: 7, Name: "Omar" },
      prompt:
        "Omar scores 9, 12 and 7 points in three games. After the fourth game the mean over all four games is 11. How many points did Omar score in the fourth game?",
      choices: ["16", "11", "5"],
      correct: "16",
    },
    {
      level: 5,
      vars: { w: "sh", N: 4, M: 12, v1: 13, v2: 14, v3: 12, Name: "Raj" },
      prompt:
        "Raj scores 13, 14 and 12 points in three games. After the fourth game the mean over all four games is 12. How many points did Raj score in the fourth game?",
      choices: ["9", "12", "3"],
      correct: "9",
    },
    {
      level: 5,
      vars: {
        w: "sh",
        N: 5,
        M: 14,
        v1: 20,
        v2: 5,
        v3: 20,
        v4: 19,
        j: 2,
        Name: "Tia",
      },
      prompt:
        "Tia scores 20, 5, 20 and 19 points in four games. After the fifth game the mean over all five games is 14. How many points did Tia score in the fifth game?",
      choices: ["6", "14", "1"],
      correct: "6",
    },
    {
      level: 5,
      vars: { w: "sh", N: 4, M: 14, v1: 20, v2: 14, v3: 17, Name: "Uma" },
      prompt:
        "Uma scores 20, 14 and 17 points in three games. After the fourth game the mean over all four games is 14. How many points did Uma score in the fourth game?",
      choices: ["5", "14", "3"],
      correct: "5",
    },
    {
      level: 5,
      vars: { w: "sh", N: 4, M: 8, v1: 3, v2: 3, v3: 10, j: 3, Name: "Zoe" },
      prompt:
        "Zoe scores 3, 3 and 10 points in three games. After the fourth game the mean over all four games is 8. How many points did Zoe score in the fourth game?",
      choices: ["16", "8", "6"],
      correct: "16",
    },
    {
      level: 6,
      vars: {
        z: "add-one",
        dev1: "spinner",
        dev2: "die",
        sections: 5,
        a: 1,
        colour: "blue",
        die: "greater",
        v: 4,
      },
      prompt:
        "A spinner with 5 equal sections, 1 of them blue, is spun and a fair die is rolled. What is the probability of blue and a number greater than 4?",
      choices: ["1/15", "8/15", "1/30"],
      correct: "1/15",
    },
    {
      level: 6,
      vars: {
        z: "med-comp",
        dev1: "coin",
        dev2: "spinner",
        coin: "tails",
        sections: 10,
        a: 3,
        colour: "purple",
      },
      prompt:
        "A fair coin is flipped and a spinner with 10 equal sections, 3 of them purple, is spun. What is the probability of tails and purple?",
      choices: ["3/20", "1/3", "7/20"],
      correct: "3/20",
    },
    {
      level: 6,
      vars: {
        z: "add-med",
        dev1: "spinner",
        dev2: "coin",
        sections: 4,
        a: 1,
        colour: "green",
        coin: "heads",
      },
      prompt:
        "A spinner with 4 equal sections, 1 of them green, is spun and a fair coin is flipped. What is the probability of green and heads?",
      choices: ["1/8", "3/4", "1/3"],
      correct: "1/8",
    },
    {
      level: 6,
      vars: {
        z: "one-comp",
        dev1: "die",
        dev2: "spinner",
        die: "parity",
        parity: "even",
        sections: 3,
        a: 2,
        colour: "yellow",
      },
      prompt:
        "A fair die is rolled and a spinner with 3 equal sections, 2 of them yellow, is spun. What is the probability of an even number and yellow?",
      choices: ["1/3", "1/18", "1/6"],
      correct: "1/3",
    },
    {
      level: 7,
      vars: { j: 2, z: "all-swap", menu: "cafe", c1: 3, c2: 4, c3: 5, i: 1 },
      prompt:
        "A cafe offers 3 sandwiches, 4 drinks and 5 cakes. A lunch deal is one sandwich and one drink. How many different lunch deals are there?",
      choices: ["12", "60", "20"],
      correct: "12",
    },
    {
      level: 7,
      vars: {
        j: 3,
        z: "all-sum",
        menu: "restaurant",
        c1: 2,
        c2: 3,
        c3: 4,
        c4: 5,
        i: 2,
      },
      prompt:
        "A restaurant offers 2 starters, 3 mains, 4 puddings and 5 drinks. A set meal is one starter, one main and one pudding. How many different set meals are there?",
      choices: ["24", "120", "9"],
      correct: "24",
    },
    {
      level: 7,
      vars: {
        j: 3,
        z: "swap-drop",
        menu: "bakery",
        c1: 5,
        c2: 2,
        c3: 3,
        c4: 6,
        i: 3,
      },
      prompt:
        "A bakery sells 5 breads, 2 spreads, 3 fruits and 6 juices. A breakfast box is one bread, one spread and one fruit. How many different breakfast boxes are there?",
      choices: ["30", "60", "10"],
      correct: "30",
    },
    {
      level: 8,
      vars: { z: "rep-num", bag: "pebbles", r: 4, b: 3, ca: "grey" },
      prompt:
        "A bag holds 4 grey pebbles and 3 white pebbles. Two are taken at random, without replacement. What is the probability that both are grey?",
      choices: ["2/7", "16/49", "12/49"],
      correct: "2/7",
    },
    {
      level: 9,
      vars: { form: "E", z: "den-div", s: 8, a: 3, n: 48, colour: "blue" },
      prompt:
        "A spinner has 8 equal sections, 3 of them blue. It is spun 48 times. About how many blue results should you expect?",
      choices: ["18", "6", "16"],
      correct: "18",
    },
    {
      level: 10,
      vars: { form: "C", z: "perm-addf", group: "choir", n: 7, r: 3 },
      prompt:
        "A choir has 7 singers. 3 of them are chosen for a small group. Order does not matter. How many different small groups are possible?",
      choices: ["35", "210", "18"],
      correct: "35",
    },
    {
      level: 10,
      vars: { form: "C", z: "divr-mult", group: "class", n: 8, r: 4 },
      prompt:
        "A class has 8 pupils. 4 of them are chosen for a team. Order does not matter. How many different teams are possible?",
      choices: ["70", "420", "32"],
      correct: "70",
    },
    {
      level: 10,
      vars: { form: "C", z: "perm-divr", group: "crew", n: 7, r: 4 },
      prompt:
        "A crew has 7 sailors. 4 of them are chosen for a watch. Order does not matter. How many different watches are possible?",
      choices: ["35", "840", "210"],
      correct: "35",
    },
    {
      level: 10,
      vars: { form: "P", z: "comb-addf", group: "squad", n: 7, r: 2 },
      prompt:
        "A squad has 7 players. 2 of them are chosen for first and second place. How many different results are possible?",
      choices: ["42", "21", "13"],
      correct: "42",
    },
    {
      level: 10,
      vars: { form: "P", z: "pow-fact", group: "band", n: 8, r: 3 },
      prompt:
        "A band has 8 players. 3 of them are chosen for first, second and third place. How many different results are possible?",
      choices: ["336", "512", "40,320"],
      correct: "336",
    },
    {
      level: 10,
      vars: { form: "P", z: "addf-pow", group: "camp", n: 6, r: 3 },
      prompt:
        "A camp has 6 leaders. 3 of them are chosen for first, second and third place. How many different results are possible?",
      choices: ["120", "15", "216"],
      correct: "120",
    },
  ],
} satisfies Examples;
