import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { form: "Q", v: "SA", a: 2, b: -2, c: -5, n: -6 },
      { form: "Q", v: "SM", a: 5, b: -1, c: -12, n: -1 },
      { form: "R", v: "PO", d: -3, n: 4, t: -5 },
    ],
    2: [
      { form: "F", a: -12, k: 2 },
      { form: "S", v: "dir", shape: "D", a: -17 },
      { form: "G", v: "bnd", h: 6, k: -11, s: -1 },
    ],
    3: [
      { form: "N", v: "OP", a: 5, b: -7, c: 5, n: -5 },
      { form: "X", w: "O", a: -4, b: 5, c: 2 },
      { form: "X", w: "P", a: -6, b: 6, c: 9 },
    ],
    4: [
      { form: "L", w: "ord", a: 6, b: -5 },
      { form: "L", w: "rec", a: 7, b: 5 },
      { form: "R", w: "sgn", k: 4, d: -6 },
    ],
    5: [
      { form: "D", h: -6, k: 9 },
      { form: "E", parent: "x²", h: 3, k: -1 },
      { form: "R", a: 2, b: -9, c: 6, ax: "x" },
    ],
    6: [
      {
        form: "G",
        dir: "up",
        v: "LF",
        context: "an investment",
        P: 750,
        r: 5,
        t: 6,
      },
      {
        form: "G",
        dir: "down",
        v: "FE",
        context: "a dose in the blood",
        P: 450,
        r: 8,
        t: 3,
      },
      {
        form: "H",
        dir: "half",
        v: "IE",
        context: "a pollutant",
        P: 200,
        h: 2,
        q: 2.5,
      },
    ],
    7: [
      { form: "C", b: 2, p: 9 },
      { form: "K", b: 5, p: 3 },
      { form: "V", base: "b", arg: "recip", v: "UD", b: 2, p: 10 },
    ],
    8: [
      { form: "N", z: "hi", b: 10, A: 21, B: 4, C: 14 },
      { form: "X", e: "expand", w: "div", b: 10, m: 4, r: 1 },
      { form: "G", op: "prod", v: "MQ", z: "lo", A: 3, B: 7 },
    ],
    9: [
      { form: "S", pair: "SC", b: 7, m: 4, K: 1, Nn: -4 },
      { form: "L", pair: "QI", b: 5, N: 495 },
      { form: "D", pair: "PT", context: "a town's people", g: 2, r: 20 },
    ],
    10: [
      { form: "P", pair: "RS", b: 3, k: 3, v: 3, X: 9 },
      { form: "P", pair: "RF", b: 10, k: 2, v: 4, X: 23 },
      { form: "D", pair: "NV", b: 2, k: 5, j: 8 },
    ],
  },
  extra: [
    {
      level: 1,
      vars: { form: "Q", v: "AM", a: -3, b: 4, c: -7, n: -2 },
      prompt: "f(x) = −3x² + 4x − 7. What is f(−2)?",
      choices: ["−27", "−11", "21"],
      correct: "−27",
    },
    {
      level: 1,
      vars: { form: "R", v: "OZ", d: -5, n: 2, t: 2 },
      prompt: "f(x) = 28/(x + 5). What is f(2)?",
      choices: ["4", "19", "14"],
      correct: "4",
    },
    {
      level: 1,
      vars: { form: "R", v: "PZ", d: 2, n: 4, t: 1 },
      prompt: "f(x) = 12/(x − 2). What is f(4)?",
      choices: ["6", "2", "3"],
      correct: "6",
    },
    {
      level: 2,
      vars: { form: "S", v: "bnd", shape: "L", a: 7 },
      prompt: "What is the domain of f(x) = √(x − 7)?",
      choices: ["x ≥ 7", "x ≥ −7", "x ≥ 0"],
      correct: "x ≥ 7",
    },
    {
      level: 2,
      vars: { form: "S", v: "dir", shape: "U", a: -4 },
      prompt: "What is the domain of f(x) = √(−4 − x)?",
      choices: ["x ≤ −4", "x ≥ −4", "x < −4"],
      correct: "x ≤ −4",
    },
    {
      level: 2,
      vars: { form: "S", v: "bnd", shape: "U", a: 9 },
      prompt: "What is the domain of f(x) = √(9 − x)?",
      choices: ["x ≤ 9", "x ≤ −9", "x ≤ 0"],
      correct: "x ≤ 9",
    },
    {
      level: 2,
      vars: { form: "S", v: "bnd", shape: "D", a: 3 },
      prompt: "What is the domain of f(x) = 1/√(x − 3)?",
      choices: ["x > 3", "x > −3", "x > 0"],
      correct: "x > 3",
    },
    {
      level: 2,
      vars: { form: "G", v: "dir", h: -4, k: 9, s: 1 },
      prompt: "What is the range of f(x) = (x + 4)² + 9?",
      choices: ["y ≥ 9", "y ≤ 9", "y > 9"],
      correct: "y ≥ 9",
    },
    {
      level: 2,
      vars: { form: "G", v: "bnd", h: 5, k: -3, s: 1 },
      prompt: "What is the range of f(x) = (x − 5)² − 3?",
      choices: ["y ≥ −3", "y ≥ 5", "y ≥ 3"],
      correct: "y ≥ −3",
    },
    {
      level: 2,
      vars: { form: "G", v: "dir", h: 2, k: 7, s: -1 },
      prompt: "What is the range of f(x) = −(x − 2)² + 7?",
      choices: ["y ≤ 7", "y ≥ 7", "y < 7"],
      correct: "y ≤ 7",
    },
    {
      level: 3,
      vars: { form: "N", v: "PU", a: 3, b: -2, c: 4, n: 2 },
      prompt: "f(x) = 3x − 2 and g(x) = x² + 4. What is f(g(2))?",
      choices: ["22", "32", "14"],
      correct: "22",
    },
    {
      level: 3,
      vars: { form: "N", v: "OU", a: -2, b: 5, c: -3, n: -1 },
      prompt: "f(x) = −2x + 5 and g(x) = x² − 3. What is f(g(−1))?",
      choices: ["9", "46", "0"],
      correct: "9",
    },
    {
      level: 3,
      vars: { form: "X", w: "O", a: 3, b: 1, c: 4 },
      prompt: "f(x) = 3x + 1 and g(x) = x² + 4. Write (f ∘ g)(x).",
      choices: ["3x² + 13", "3x² + 5", "9x² + 6x + 5"],
      correct: "3x² + 13",
    },
    {
      level: 3,
      vars: { form: "X", w: "P", a: -3, b: 2, c: 2 },
      prompt: "f(x) = −3x + 2 and g(x) = x² + 2. Write (f ∘ g)(x).",
      choices: ["−3x² − 4", "−3x² + 4", "−3x³ + 2x² − 6x + 4"],
      correct: "−3x² − 4",
    },
    {
      level: 3,
      vars: { form: "X", w: "P", a: 2, b: 2, c: 5 },
      prompt: "f(x) = 2x + 2 and g(x) = x² + 5. Write (f ∘ g)(x).",
      choices: ["2x² + 12", "2x² + 7", "2x³ + 2x² + 10x + 10"],
      correct: "2x² + 12",
    },
    {
      level: 3,
      vars: { form: "X", w: "O", a: 3, b: 3, c: 4 },
      prompt: "f(x) = 3x + 3 and g(x) = x² + 4. Write (f ∘ g)(x).",
      choices: ["3x² + 15", "3x² + 7", "9x² + 18x + 13"],
      correct: "3x² + 15",
    },
    {
      level: 3,
      vars: { form: "N", v: "OU", a: 2, b: 5, c: -8, n: -1 },
      prompt: "f(x) = 2x + 5 and g(x) = x² − 8. What is f(g(−1))?",
      choices: ["−9", "1", "−1"],
      correct: "−9",
    },
    {
      level: 3,
      vars: { form: "X", w: "O", a: -2, b: -1, c: -2 },
      prompt: "f(x) = −2x − 1 and g(x) = x² − 2. Write (f ∘ g)(x).",
      choices: ["−2x² + 3", "−2x² − 3", "4x² + 4x − 1"],
      correct: "−2x² + 3",
    },
    {
      level: 3,
      vars: { form: "X", w: "P", a: -3, b: 3, c: 3 },
      prompt: "f(x) = −3x + 3 and g(x) = x² + 3. Write (f ∘ g)(x).",
      choices: ["−3x² − 6", "−3x² + 6", "−3x³ + 3x² − 9x + 9"],
      correct: "−3x² − 6",
    },
    {
      level: 4,
      vars: { form: "R", w: "rec", k: 9, d: 4 },
      prompt: "f(x) = 9/(x − 4). What is f⁻¹(x)?",
      choices: ["f⁻¹(x) = 9/x + 4", "f⁻¹(x) = 9/x − 4", "f⁻¹(x) = (x − 4)/9"],
      correct: "f⁻¹(x) = 9/x + 4",
    },
    {
      level: 4,
      vars: { form: "L", w: "ord", a: 3, b: 8 },
      prompt: "f(x) = 3x + 8. What is f⁻¹(x)?",
      choices: ["f⁻¹(x) = (x − 8)/3", "f⁻¹(x) = (x + 8)/3", "f⁻¹(x) = x/3 − 8"],
      correct: "f⁻¹(x) = (x − 8)/3",
    },
    {
      level: 5,
      vars: { form: "E", parent: "|x|", h: -6, k: 2 },
      prompt:
        "The graph of y = |x| is moved 6 units left and 2 units up. Which is the new function?",
      choices: ["y = |x + 6| + 2", "y = |x − 6| + 2", "y = |x − 6| − 2"],
      correct: "y = |x + 6| + 2",
    },
    {
      level: 5,
      vars: { form: "E", parent: "x³", h: -4, k: -7 },
      prompt:
        "The graph of y = x³ is moved 4 units left and 7 units down. Which is the new function?",
      choices: ["y = (x + 4)³ − 7", "y = (x − 4)³ − 7", "y = (x − 4)³ + 7"],
      correct: "y = (x + 4)³ − 7",
    },
    {
      level: 5,
      vars: { form: "R", a: -1, b: 5, c: -8, ax: "y" },
      prompt:
        "f(x) = −x² + 5x − 8 and g(x) = −x² − 5x − 8. How is the graph of g related to the graph of f?",
      choices: [
        "reflected in the y-axis",
        "reflected in the x-axis",
        "reflected in the line y = x",
      ],
      correct: "reflected in the y-axis",
    },
    {
      level: 5,
      vars: { form: "D", h: 1, k: -1 },
      prompt:
        "g(x) = f(x − 1) − 1. How does the graph of g compare with the graph of f?",
      choices: [
        "1 unit right and 1 unit down",
        "1 unit left and 1 unit down",
        "1 unit left and 1 unit up",
      ],
      correct: "1 unit right and 1 unit down",
    },
    {
      level: 6,
      vars: {
        form: "G",
        dir: "up",
        v: "LE",
        context: "a savings account",
        P: 400,
        r: 10,
        t: 3,
      },
      prompt:
        "A savings account holds $400. It gains 10% each year. How much is in it after 3 years? Round to 2 dp.",
      choices: ["$532.40", "$520.00", "$585.64"],
      correct: "$532.40",
    },
    {
      level: 6,
      vars: {
        form: "G",
        dir: "up",
        v: "FE",
        context: "a reed bed",
        P: 500,
        r: 20,
        t: 2,
      },
      prompt:
        "A reed bed covers 500 m². It grows by 20% each year. How much does it cover after 2 years? Round to 2 dp.",
      choices: ["720.00 m²", "320.00 m²", "864.00 m²"],
      correct: "720.00 m²",
    },
    {
      level: 6,
      vars: {
        form: "G",
        dir: "up",
        v: "LF",
        context: "a town's water use",
        P: 600,
        r: 12,
        t: 4,
      },
      prompt:
        "A town uses 600 kL of water a day. Its use grows by 12% each year. How much will it use a day after 4 years? Round to 2 dp.",
      choices: ["944.11 kL", "888.00 kL", "359.82 kL"],
      correct: "944.11 kL",
    },
    {
      level: 6,
      vars: {
        form: "G",
        dir: "down",
        v: "LE",
        context: "a machine's value",
        P: 800,
        r: 10,
        t: 3,
      },
      prompt:
        "A machine is worth $800. It loses 10% of its value each year. What is it worth after 3 years? Round to 2 dp.",
      choices: ["$583.20", "$560.00", "$524.88"],
      correct: "$583.20",
    },
    {
      level: 6,
      vars: {
        form: "G",
        dir: "down",
        v: "LF",
        context: "a pond",
        P: 900,
        r: 15,
        t: 4,
      },
      prompt:
        "A pond holds 900 kL of water. It loses 15% each week. How much is left after 4 weeks? Round to 2 dp.",
      choices: ["469.81 kL", "360.00 kL", "1,574.11 kL"],
      correct: "469.81 kL",
    },
    {
      level: 6,
      vars: {
        form: "G",
        dir: "down",
        v: "FE",
        context: "a forest",
        P: 250,
        r: 20,
        t: 3,
      },
      prompt:
        "A forest covers 250 km². It shrinks by 20% each year. How much is left after 3 years? Round to 2 dp.",
      choices: ["128.00 km²", "432.00 km²", "102.40 km²"],
      correct: "128.00 km²",
    },
    {
      level: 6,
      vars: {
        form: "H",
        dir: "half",
        v: "IF",
        context: "a radioactive sample",
        P: 800,
        h: 3,
        q: 2,
      },
      prompt:
        "A radioactive sample weighing 800 g has a half-life of 3 years. How much is left after 6 years? Round to 2 dp.",
      choices: ["200.00 g", "12.50 g", "400.00 g"],
      correct: "200.00 g",
    },
    {
      level: 6,
      vars: {
        form: "H",
        dir: "half",
        v: "FE",
        context: "a tracer",
        P: 300,
        h: 2,
        q: 3.5,
      },
      prompt:
        "A tracer dose of 300 mg has a half-life of 2 hours. How much is left after 7 hours? Round to 2 dp.",
      choices: ["26.52 mg", "53.03 mg", "13.26 mg"],
      correct: "26.52 mg",
    },
    {
      level: 6,
      vars: {
        form: "H",
        dir: "double",
        v: "IE",
        context: "a yeast culture",
        P: 250,
        h: 4,
        q: 1.5,
      },
      prompt:
        "A yeast culture weighing 250 g doubles every 4 hours. How much is there after 6 hours? Round to 2 dp.",
      choices: ["707.11 g", "16,000.00 g", "1,414.21 g"],
      correct: "707.11 g",
    },
    {
      level: 6,
      vars: {
        form: "H",
        dir: "double",
        v: "IF",
        context: "a colony",
        P: 350,
        h: 2,
        q: 2,
      },
      prompt:
        "A bacteria colony covering 350 mm² doubles every 2 hours. How much does it cover after 4 hours? Round to 2 dp.",
      choices: ["1,400.00 mm²", "5,600.00 mm²", "700.00 mm²"],
      correct: "1,400.00 mm²",
    },
    {
      level: 6,
      vars: {
        form: "H",
        dir: "double",
        v: "FE",
        context: "an algae mat",
        P: 200,
        h: 2,
        q: 2.5,
      },
      prompt:
        "An algae mat covering 200 m² doubles every 2 days. How much does it cover after 5 days? Round to 2 dp.",
      choices: ["1,131.37 m²", "565.69 m²", "2,262.74 m²"],
      correct: "1,131.37 m²",
    },
    {
      level: 7,
      vars: { form: "V", base: "b", arg: "whole", v: "UB", b: 3, p: 5 },
      prompt: "What is log₃ 243?",
      choices: ["5", "6", "3"],
      correct: "5",
    },
    {
      level: 7,
      vars: { form: "V", base: "b", arg: "whole", v: "DB", b: 10, p: 4 },
      prompt: "What is log₁₀ 10,000?",
      choices: ["4", "3", "10"],
      correct: "4",
    },
    {
      level: 7,
      vars: { form: "V", base: "b", arg: "recip", v: "UB", b: 7, p: 3 },
      prompt: "What is log₇(1/343)?",
      choices: ["−3", "−2", "7"],
      correct: "−3",
    },
    {
      level: 7,
      vars: { form: "V", base: "e", arg: "whole", v: "DO", p: 5 },
      prompt: "What is ln(e⁵)?",
      choices: ["5", "4", "1"],
      correct: "5",
    },
    {
      level: 7,
      vars: { form: "V", base: "e", arg: "recip", v: "UO", p: 3 },
      prompt: "What is ln(1/e³)?",
      choices: ["−3", "−2", "1"],
      correct: "−3",
    },
    {
      level: 7,
      vars: { form: "V", base: "e", arg: "whole", v: "UD", p: 2 },
      prompt: "What is ln(e²)?",
      choices: ["2", "3", "1"],
      correct: "2",
    },
    {
      level: 7,
      vars: { form: "C", b: 22, p: 3 },
      prompt: "Write 22³ = 10,648 in logarithmic form.",
      choices: ["log₂₂ 10,648 = 3", "log₁₀₆₄₈ 22 = 3", "log₁₀₆₄₈ 3 = 22"],
      correct: "log₂₂ 10,648 = 3",
    },
    {
      level: 7,
      vars: { form: "K", b: 3, p: 7 },
      prompt: "Write log₃ 2,187 = 7 in exponential form.",
      choices: ["3⁷ = 2,187", "2,187⁷ = 3", "2,187³ = 7"],
      correct: "3⁷ = 2,187",
    },
    {
      level: 8,
      vars: { form: "N", z: "lo", b: 2, A: 12, B: 10, C: 4 },
      prompt: "Write log₂ 12 + log₂ 10 − log₂ 4 as a single logarithm.",
      choices: ["log₂ 30", "log₂ 18", "log₂ 116"],
      correct: "log₂ 30",
    },
    {
      level: 8,
      vars: { form: "X", e: "expand", w: "pow", b: 3, m: 5, r: 2 },
      prompt:
        "For x > 0 and y > 0, write log₃(x⁵/y²) as a sum or difference of logarithms.",
      choices: [
        "5 log₃ x − 2 log₃ y",
        "5 log₃ x + 2 log₃ y",
        "(log₃ x)⁵ − 2 log₃ y",
      ],
      correct: "5 log₃ x − 2 log₃ y",
    },
    {
      level: 8,
      vars: { form: "X", e: "condense", w: "pow", b: 5, m: 3, r: 4 },
      prompt:
        "For x > 0 and y > 0, write 3 log₅ x − 4 log₅ y as a single logarithm.",
      choices: ["log₅(x³/y⁴)", "log₅(x³y⁴)", "log₅(3x − 4y)"],
      correct: "log₅(x³/y⁴)",
    },
    {
      level: 8,
      vars: { form: "X", e: "condense", w: "div", b: 2, m: 2, r: 1 },
      prompt:
        "For x > 0 and y > 0, write 2 log₂ x − log₂ y as a single logarithm.",
      choices: ["log₂(x²/y)", "log₂(x²y)", "log₂(x²)/log₂(y)"],
      correct: "log₂(x²/y)",
    },
    {
      level: 8,
      vars: { form: "G", op: "prod", v: "QS", z: "hi", A: 15, B: 2 },
      prompt:
        "Take log₁₀ 15 ≈ 1.18 and log₁₀ 2 ≈ 0.30. Estimate log₁₀(15 × 2) to 2 dp.",
      choices: ["1.48", "3.93", "0.88"],
      correct: "1.48",
    },
    {
      level: 8,
      vars: { form: "G", op: "quot", v: "QA", A: 11, B: 5 },
      prompt:
        "Take log₁₀ 11 ≈ 1.04 and log₁₀ 5 ≈ 0.70. Estimate log₁₀(11/5) to 2 dp.",
      choices: ["0.34", "1.49", "1.74"],
      correct: "0.34",
    },
    {
      level: 8,
      vars: { form: "G", op: "quot", v: "AR", A: 7, B: 2 },
      prompt:
        "Take log₁₀ 7 ≈ 0.85 and log₁₀ 2 ≈ 0.30. Estimate log₁₀(7/2) to 2 dp.",
      choices: ["0.55", "1.15", "−0.55"],
      correct: "0.55",
    },
    {
      level: 8,
      vars: { form: "G", op: "quot", v: "QR", A: 13, B: 3 },
      prompt:
        "Take log₁₀ 13 ≈ 1.11 and log₁₀ 3 ≈ 0.48. Estimate log₁₀(13/3) to 2 dp.",
      choices: ["0.63", "2.31", "−0.63"],
      correct: "0.63",
    },
    {
      level: 8,
      vars: { form: "G", op: "pow", v: "PV", A: 3, m: 3 },
      prompt: "Take log₁₀ 3 ≈ 0.48. Estimate log₁₀(3³) to 2 dp.",
      choices: ["1.44", "0.11", "0.16"],
      correct: "1.44",
    },
    {
      level: 8,
      vars: { form: "G", op: "pow", v: "SV", A: 11, m: 4 },
      prompt: "Take log₁₀ 11 ≈ 1.04. Estimate log₁₀(11⁴) to 2 dp.",
      choices: ["4.16", "5.04", "0.26"],
      correct: "4.16",
    },
    {
      level: 8,
      vars: { form: "G", op: "pow", v: "PS", A: 2, m: 2 },
      prompt: "Take log₁₀ 2 ≈ 0.30. Estimate log₁₀(2²) to 2 dp.",
      choices: ["0.60", "0.09", "2.30"],
      correct: "0.60",
    },
    {
      level: 9,
      vars: { form: "S", pair: "CO", b: 2, m: 3, K: 2, Nn: 5 },
      prompt: "Solve 2^(3x + 15) = 64.",
      choices: ["x = −3", "x = −9", "x = −13"],
      correct: "x = −3",
    },
    {
      level: 9,
      vars: { form: "S", pair: "SO", b: 5, m: 2, K: 3, Nn: -2 },
      prompt: "Solve 5^(2x − 4) = 15,625.",
      choices: ["x = 5", "x = 1", "x = 7"],
      correct: "x = 5",
    },
    {
      level: 9,
      vars: { form: "L", pair: "QD", b: 2, N: 100 },
      prompt: "Solve 2^x = 100. Round to 2 dp.",
      choices: ["x = 6.64", "x = 1.70", "x = 50.00"],
      correct: "x = 6.64",
    },
    {
      level: 9,
      vars: { form: "L", pair: "ID", b: 3, N: 50 },
      prompt: "Solve 3^x = 50. Round to 2 dp.",
      choices: ["x = 3.56", "x = 0.28", "x = 16.67"],
      correct: "x = 3.56",
    },
    {
      level: 9,
      vars: { form: "D", pair: "PQ", context: "an investment", g: 3, r: 10 },
      prompt:
        "An investment of $2,000 grows 10% a year. To 2 dp, how many years until it triples?",
      choices: ["11.53 years", "20.00 years", "0.44 years"],
      correct: "11.53 years",
    },
    {
      level: 9,
      vars: {
        form: "D",
        pair: "QT",
        context: "a bacteria colony",
        g: 2,
        r: 25,
      },
      prompt:
        "A bacteria colony of 800 cells grows 25% an hour. To 2 dp, how many hours until it doubles?",
      choices: ["3.11 hours", "0.20 hours", "8.00 hours"],
      correct: "3.11 hours",
    },
    {
      level: 9,
      vars: { form: "D", pair: "PT", context: "site traffic", g: 3, r: 5 },
      prompt:
        "A website's daily traffic of 3,000 visits grows 5% a month. To 2 dp, how many months until it triples?",
      choices: ["22.52 months", "40.00 months", "60.00 months"],
      correct: "22.52 months",
    },
    {
      level: 10,
      vars: { form: "P", pair: "SF", b: 2, k: 5, v: 4, X: 6 },
      prompt: "Solve log₂ (x + 2) + log₂ (x − 2) = 5.",
      choices: ["x = 6", "x = 30", "x = 4"],
      correct: "x = 6",
    },
    {
      level: 10,
      vars: { form: "D", pair: "NK", b: 3, k: 2, j: 5 },
      prompt: "Solve log₃ x − log₃ (x − 40) = 2.",
      choices: ["x = 45", "x = 5", "x = 80"],
      correct: "x = 45",
    },
    {
      level: 10,
      vars: { form: "D", pair: "VK", b: 10, k: 3, j: 2 },
      prompt: "Solve log₁₀ x − log₁₀ (x − 1,998) = 3.",
      choices: ["x = 2,000", "x = −2", "x = 2,997"],
      correct: "x = 2,000",
    },
  ],
} satisfies Examples;
