import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { form: "N", v: "up", a: -1, d: 4, n: 29 },
      { form: "N", v: "up", a: 1, d: -8, n: 28 },
      { form: "T", n: 8, t: -3, s: 5 },
    ],
    2: [
      { form: "N", pair: "AX", r: -3, a: -7, n: 6 },
      { form: "P", pair: "MA", r: 2, a: 6, n: 6 },
      { form: "P", pair: "AX", r: -2, a: 3, n: 10 },
    ],
    3: [
      { form: "F", pair: "LW", a: -5, d: 4, n: 10 },
      { form: "F", pair: "LQ", a: 12, d: -8, n: 17 },
      { form: "R", pair: "WP", a: 30, d: 6, n: 11, place: "theatre" },
    ],
    4: [
      { form: "F", pair: "WQ", r: 3, a: -10, n: 4 },
      { form: "I", pair: "HR", r: [-2, 5], c: 5 },
      {
        form: "C",
        r: [3, 5],
        r1: [-3, 2],
        r2: [-1, 1],
        c: 2,
        c1: 6,
        c2: 40,
        s0: -1,
        s1: 1,
        s2: -1,
      },
    ],
    5: [
      { body: "linear", v: "X", L: 1, n: 8, p: 2, q: 1 },
      { body: "square", v: "X", L: 0, n: 4, q: 2 },
      { body: "linear", v: "E", L: 0, n: 6, p: -1, q: 8 },
    ],
    6: [
      { form: "A", pair: "OmP", s: 3, c: -1, m: 2, N: 5 },
      { form: "F", pair: "OmW", u: 8, v: 5, j: 1, N: 7 },
      { form: "F", pair: "OmR", u: 4, v: 2, j: 2, N: 7 },
    ],
    7: [
      { form: "LL", v: "V", T: "T1", h: -5, a: -3, z: -8, c: 3 },
      { form: "LL", v: "H", h: 9, a: 3, z: -8, c: 3 },
      { form: "LQ", v: "H", h: 2, a: 5, z: -3 },
    ],
    8: [
      { form: "F", T: "T1", r1: 4, r2: -6, r3: 1, r: 4, X: 12 },
      { form: "F", T: "T1", r1: -4, r2: 2, r3: 3, r: -4, X: 6 },
      { form: "R", b: 8, c: -9, d: -4, k: 2 },
    ],
    9: [
      { form: "A", a: -4, b: -7, p: -5, delta: 6, c: 0 },
      { form: "D", a: 4, b: 9, p: 3, delta: 4, c: -12 },
      { form: "D", a: -3, b: -9, p: 3, delta: 6, c: 6 },
    ],
    10: [
      { form: "V1", pair: "PW", n: 7, k: 2, b: 3 },
      { form: "V1", pair: "PK", n: 7, k: 4, b: -2 },
      { form: "V2", pair: "AK", n: 6, k: 2, a: 2, b: -1 },
    ],
  },
  extra: [
    {
      level: 1,
      vars: { form: "N", v: "down", a: 5, d: -3, n: 12 },
      prompt: "An arithmetic sequence has a₁ = 5 and d = −3. What is a₁₂?",
      choices: ["−28", "−25", "52"],
      correct: "−28",
    },
    {
      level: 1,
      vars: { form: "T", n: 4, t: 1, s: -5 },
      prompt:
        "An arithmetic sequence has a₁ = −15 and a₄ = −3. What is the common difference d?",
      choices: ["4", "3", "−1"],
      correct: "4",
    },
    {
      level: 1,
      vars: { form: "T", n: 5, t: -1, s: 4 },
      prompt:
        "An arithmetic sequence has a₁ = 16 and a₅ = −4. What is the common difference d?",
      choices: ["−5", "−4", "−1"],
      correct: "−5",
    },
    {
      level: 2,
      vars: { form: "N", pair: "MX", r: 2, a: 5, n: 7 },
      prompt: "What is a₇ in the geometric sequence 5, 10, 20, …?",
      choices: ["320", "60", "31,250"],
      correct: "320",
    },
    {
      level: 3,
      vars: { form: "R", pair: "LQ", a: 12, d: 4, n: 9, place: "stadium" },
      prompt:
        "A stadium has 12 seats in the front row and 4 more seats in each row behind it. How many seats are in the first 9 rows?",
      choices: ["252", "270", "300"],
      correct: "252",
    },
    {
      level: 3,
      vars: {
        form: "R",
        pair: "WP",
        a: 15,
        d: 4,
        n: 10,
        place: "concert hall",
      },
      prompt:
        "A concert hall has 15 seats in the front row and 4 more seats in each row behind it. How many seats are in the first 10 rows?",
      choices: ["330", "297", "279"],
      correct: "330",
    },
    {
      level: 3,
      vars: {
        form: "R",
        pair: "LW",
        a: 20,
        d: 6,
        n: 8,
        place: "lecture hall",
      },
      prompt:
        "A lecture hall has 20 seats in the front row and 6 more seats in each row behind it. How many seats are in the first 8 rows?",
      choices: ["328", "352", "287"],
      correct: "328",
    },
    {
      level: 3,
      vars: { form: "F", pair: "WP", a: 7, d: -6, n: 9 },
      prompt: "What is the sum of the first 9 terms of 7, 1, −5, …?",
      choices: ["−153", "−136", "−112"],
      correct: "−153",
    },
    {
      level: 4,
      vars: { form: "F", pair: "WP", r: 2, a: 3, n: 6 },
      prompt: "What is the sum of the first 6 terms of 3, 6, 12, …?",
      choices: ["189", "297", "93"],
      correct: "189",
    },
    {
      level: 4,
      vars: { form: "I", pair: "GX", r: [1, 3], c: 1 },
      prompt: "9 + 3 + 1 + … = ?",
      choices: ["27/2", "27/4", "63/4"],
      correct: "27/2",
    },
    {
      level: 4,
      vars: { form: "I", pair: "JG", r: [-1, 2], c: 2 },
      prompt: "8 − 4 + 2 − … = ?",
      choices: ["16/3", "40/3", "16"],
      correct: "16/3",
    },
    {
      level: 4,
      vars: {
        form: "C",
        r: [-2, 5],
        r1: [-2, 1],
        r2: [3, 2],
        c: 2,
        c1: 13,
        c2: 6,
        s0: 1,
        s1: -1,
        s2: 1,
      },
      prompt: "Which infinite series has a finite sum?",
      choices: ["50 − 20 + 8 − …", "−13 + 26 − 52 + …", "24 + 36 + 54 + …"],
      correct: "50 − 20 + 8 − …",
    },
    {
      level: 5,
      vars: { body: "square", v: "E", L: 1, n: 5, q: -3 },
      prompt: "What is Σ (k² − 3) for k = 1 to 5?",
      choices: ["40", "52", "18"],
      correct: "40",
    },
    {
      level: 6,
      vars: { form: "A", pair: "OmG", s: 5, c: 2, m: 2, N: 5 },
      prompt: "a₁ = 5 and aₙ = 2aₙ₋₁ + 2. What is a₅?",
      choices: ["110", "54", "80"],
      correct: "110",
    },
    {
      level: 6,
      vars: { form: "A", pair: "OpG", s: -2, c: 5, m: 3, N: 4 },
      prompt: "a₁ = −2 and aₙ = 3aₙ₋₁ + 5. What is a₄?",
      choices: ["11", "38", "−54"],
      correct: "11",
    },
    {
      level: 6,
      vars: { form: "A", pair: "OpP", s: 4, c: -6, m: 2, N: 6 },
      prompt: "a₁ = 4 and aₙ = 2aₙ₋₁ − 6. What is a₆?",
      choices: ["−58", "−122", "−244"],
      correct: "−58",
    },
    {
      level: 6,
      vars: { form: "F", pair: "OpW", u: 2, v: -5, j: 1, N: 5 },
      prompt: "a₁ = 2, a₂ = −5 and aₙ = aₙ₋₁ + aₙ₋₂. What is a₅?",
      choices: ["−11", "−19", "−40"],
      correct: "−11",
    },
    {
      level: 6,
      vars: { form: "F", pair: "OpR", u: -3, v: 4, j: 2, N: 6 },
      prompt: "a₁ = −3, a₂ = 4 and aₙ = aₙ₋₁ + 2aₙ₋₂. What is a₆?",
      choices: ["14", "18", "−20"],
      correct: "14",
    },
    {
      level: 7,
      vars: { form: "LL", v: "V", T: "T2", h: 4, a: 2, z: 3, c: 2 },
      prompt: "What are the asymptotes of f(x) = (2x − 6)/(2x − 8)?",
      choices: ["x = 4 and y = 1", "x = 3 and y = 1", "x = −3 and y = 1"],
      correct: "x = 4 and y = 1",
    },
    {
      level: 7,
      vars: { form: "LQ", v: "V", T: "T3", h: -3, a: 4, z: 5 },
      prompt: "What are the asymptotes of f(x) = (4x − 20)/(x + 3)²?",
      choices: ["x = −3 and y = 0", "x = 3 and y = 0", "x = −5 and y = 0"],
      correct: "x = −3 and y = 0",
    },
    {
      level: 8,
      vars: { form: "F", T: "T2", r1: 2, r2: 3, r3: -5, r: 2, X: 6 },
      prompt: "Which is a factor of x³ − 19x + 30?",
      choices: ["(x − 2)", "(x − 6)", "(x + 6)"],
      correct: "(x − 2)",
    },
    {
      level: 8,
      vars: { form: "F", T: "T3", r1: -1, r2: -1, r3: 4, r: -1, X: 2 },
      prompt: "Which is a factor of x³ − 2x² − 7x − 4?",
      choices: ["(x + 1)", "(x − 1)", "(x + 2)"],
      correct: "(x + 1)",
    },
    {
      level: 8,
      vars: { form: "R", b: 3, c: -4, d: -7, k: -3 },
      prompt:
        "What is the remainder when x³ + 3x² − 4x − 7 is divided by x + 3?",
      choices: ["5", "35", "−4"],
      correct: "5",
    },
    {
      level: 8,
      vars: { form: "R", b: 0, c: -5, d: 2, k: 3 },
      prompt: "What is the remainder when x³ − 5x + 2 is divided by x − 3?",
      choices: ["14", "−10", "4"],
      correct: "14",
    },
    {
      level: 9,
      vars: { form: "D", a: 1, b: 9, p: -4, delta: 2, c: -2 },
      prompt:
        "For f(x) = x² + 9x − 2, what is (f(−4 + h) − f(−4))/h when h = 2?",
      choices: ["3", "10", "−3"],
      correct: "3",
    },
    {
      level: 10,
      vars: { form: "V1", pair: "WK", n: 4, k: 1, b: 3 },
      prompt: "What is the coefficient of x in (x + 3)⁴?",
      choices: ["108", "12", "162"],
      correct: "108",
    },
    {
      level: 10,
      vars: { form: "V2", pair: "AW", n: 5, k: 2, a: 2, b: 3 },
      prompt: "What is the coefficient of x² in (2x + 3)⁵?",
      choices: ["1,080", "270", "720"],
      correct: "1,080",
    },
    {
      level: 10,
      vars: { form: "V2", pair: "PW", n: 6, k: 2, a: 2, b: -1 },
      prompt: "What is the coefficient of x² in (2x − 1)⁶?",
      choices: ["60", "15", "240"],
      correct: "60",
    },
  ],
} satisfies Examples;
