import type { Examples } from "../support/fixtures.ts";

export default {
  levels: {
    1: [
      { pair: "SA", a: -3, b: -1, k: 57, c: -3 },
      { pair: "AM", a: 3, b: -8, k: 33, c: -1 },
      { pair: "AM", a: 3, b: 2, k: -47, c: -3 },
    ],
    2: [
      { pair: "BV", a: 1, c: -6, t: 1, s: -3 },
      { pair: "BN", a: 2, c: -2, t: -4, s: -9 },
      { pair: "VN", a: 2, c: 5, t: -4, s: -2 },
    ],
    3: [
      {
        case: "E",
        deg: [3, 3],
        a: 2,
        d: 5,
        e: -9,
        pe: 1,
        f: 2,
        pf: 2,
        topOrder: "desc",
        bottomOrder: "asc",
      },
      {
        case: "B",
        deg: [2, 3],
        a: 7,
        d: 5,
        e: -3,
        pe: 0,
        f: 4,
        pf: 0,
        topOrder: "asc",
        bottomOrder: "desc",
      },
      {
        case: "T",
        deg: [2, 1],
        a: -9,
        d: -1,
        e: -2,
        pe: 0,
        f: -5,
        pf: 0,
        topOrder: "desc",
        bottomOrder: "desc",
      },
    ],
    4: [
      { form: "D", v: "coef", m: 5, a: -2, n: [3, 2], b: -2, k: -9 },
      { form: "D", v: "exp", m: 3, a: 4, n: [-2, 1], b: -5, k: 5 },
      { form: "V", pair: "FL", m: 4, a: 1, b: 5, k: -9, c: 2 },
    ],
    5: [
      { form: "P", shape: "a,b", a: 2, m: 5, g: "sin x" },
      { form: "P", shape: "a,ab", a: 6, m: 4, g: "ln x" },
      { form: "Q", shape: "b,ab", a: 3, b: -3, d: -3, c: 4 },
    ],
    6: [
      { form: "T", shape: "a,b", trig: "cos", a: 2, k: 2 },
      { form: "E", shape: "b,ab", a: 3, k: 7 },
      { form: "P", shape: "a,b", a: 4, c: -3, n: 3 },
    ],
    7: [
      { cat: "I", pair: "SO", a: 2, b: -2, c: -9, p: -1 },
      { cat: "I", pair: "DO", a: 1, b: -9, c: 0, p: 2 },
      { cat: "S", pair: "FP", a: 3, b: 3, c: -8, p: 3 },
    ],
    8: [
      {
        form: "X",
        ask: "max",
        shape: "a,ab",
        answerSign: 1,
        aSign: 1,
        a: 1,
        r: 2,
        s: 6,
        k: 7,
      },
      {
        form: "X",
        ask: "min",
        shape: "a,b",
        answerSign: -1,
        aSign: 1,
        a: 2,
        r: -4,
        s: -3,
        k: -2,
      },
      { form: "I", ask: "dec", shape: "a,ab", a: 1, r: -6, s: 4, k: -1 },
    ],
    9: [
      { form: "P", shape: "a,b", m: 4, n: 2, a: -15, b: -3, k: 2 },
      {
        form: "F",
        shape: "a,b",
        trig: "sin",
        other: "recip",
        a: -3,
        b: -9,
      },
      { form: "F", shape: "b,ab", trig: "sin", other: "exp", a: -8, b: 5 },
    ],
    10: [
      {
        form: "D",
        shape: "a,b",
        X: "K",
        answerSign: -1,
        aSign: 1,
        a: 2,
        b: -3,
        c: -9,
        p: 0,
        q: 2,
      },
      {
        form: "U",
        shape: "b,ab",
        X: "B",
        answerSign: 1,
        kSign: 1,
        k: 2,
        c: 4,
        n: 2,
        p: 0,
        q: 1,
      },
      { form: "A", pair: "VK", a: 3, b: 1, c: 7, p: 1, q: 3 },
    ],
  },
} satisfies Examples;
