import { readFile, writeFile } from "node:fs/promises";
import opentype from "opentype.js";

// The logotype as outlines, so no port needs the fonts installed to show it.
// Mirrors the title screen: "Night" upright, "water." italic in mint, stacked
// on a 0.85 line height with the second line nudged right.
const FONTS = {
  upright: "art/fonts/Newsreader-Display.ttf",
  italic: "art/fonts/Newsreader-DisplayItalic.ttf",
};
const EM = 100;
const TRACKING = -0.03;
const LINES = [
  {
    text: "Night",
    font: "upright",
    x: 0,
    y: 0,
    fill: "#eef3eb",
    part: "night",
  },
  {
    text: "water.",
    font: "italic",
    x: 3,
    y: 85,
    fill: "#b9e4da",
    part: "water",
  },
];
const START = "<!-- wordmark:start -->";
const END = "<!-- wordmark:end -->";

async function load(file) {
  const bytes = await readFile(file);
  return opentype.parse(
    bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength),
  );
}

// opentype.js's own toPathData() is stateful across calls and can emit NaN.
const n = (value) => String(Math.round(value * 100) / 100);
const pathData = (path) =>
  path.commands
    .map((c) =>
      c.type === "Z"
        ? "Z"
        : c.type === "Q"
          ? `Q${n(c.x1)} ${n(c.y1)} ${n(c.x)} ${n(c.y)}`
          : c.type === "C"
            ? `C${n(c.x1)} ${n(c.y1)} ${n(c.x2)} ${n(c.y2)} ${n(c.x)} ${n(c.y)}`
            : `${c.type}${n(c.x)} ${n(c.y)}`,
    )
    .join("");

export async function outlineWordmark() {
  const fonts = Object.fromEntries(
    await Promise.all(
      Object.entries(FONTS).map(async ([name, file]) => [
        name,
        await load(file),
      ]),
    ),
  );
  const box = { x1: Infinity, y1: Infinity, x2: -Infinity, y2: -Infinity };
  const paths = LINES.map((line) => {
    const font = fonts[line.font];
    const scale = EM / font.unitsPerEm;
    const glyphs = font.stringToGlyphs(line.text);
    let cursor = line.x;
    const d = glyphs.map((glyph, k) => {
      const path = glyph.getPath(cursor, line.y, EM);
      const b = path.getBoundingBox();
      box.x1 = Math.min(box.x1, b.x1);
      box.y1 = Math.min(box.y1, b.y1);
      box.x2 = Math.max(box.x2, b.x2);
      box.y2 = Math.max(box.y2, b.y2);
      cursor += glyph.advanceWidth * scale;
      if (k < glyphs.length - 1)
        cursor +=
          (font.getKerningValue(glyph, glyphs[k + 1]) || 0) * scale +
          TRACKING * EM;
      return pathData(path);
    });
    return `<path class="${line.part}" fill="${line.fill}" d="${d.join("")}"/>`;
  });
  const group = `<g class="wordmark">${paths.join("")}</g>`;
  const pad = 2;
  const view = [
    box.x1 - pad,
    box.y1 - pad,
    box.x2 - box.x1 + pad * 2,
    box.y2 - box.y1 + pad * 2,
  ]
    .map((v) => v.toFixed(2))
    .join(" ");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${view}" width="${(box.x2 - box.x1 + pad * 2).toFixed(0)}" height="${(box.y2 - box.y1 + pad * 2).toFixed(0)}">
  <!-- Generated by scripts/build-art.mjs from art/fonts (Newsreader Display, 1 em = ${EM} units). Edit LINES in scripts/support/wordmark.mjs, not this file. -->
  <title>Nightwater</title>
  ${group}
</svg>
`;
  await writeFile("art/wordmark.svg", svg);
  const og = await readFile("art/og-image.svg", "utf8").catch(() => null);
  if (og) {
    const start = og.indexOf(START),
      end = og.indexOf(END);
    if (start < 0 || end < start)
      throw new Error("art/og-image.svg needs wordmark:start/end markers");
    const synced = og.slice(0, start + START.length) + group + og.slice(end);
    if (synced !== og) await writeFile("art/og-image.svg", synced);
  }
  return { box, group };
}
